# Data Cleaning
In this stage, you will read in the raw data and perform any necessary reshaping, combining, and cleaning of the data. Though this stage is not explicitly an exploratory stage, you will learn a lot about the content of the data throughout the course of this notebook.

### Imports

For your convenience, we have included a few pre-written functions, which you might find useful in your analysis. They are by no means necessary, but feel free to use any or all of them. The code for these functions can be found in /src

In [1]:
import pandas as pd
import os
import sys

In [2]:
src_path = os.path.abspath('../src/')
sys.path.append(src_path)

from data_cleaning import *

In [3]:
# Imports numpy
import numpy as np

In [4]:
# Imports display and HTML from IPython.display and codes function that will show long dataframes in a scrollable window
from IPython.display import display, HTML
def display_scrollable_df(df, height=300):
    display(HTML(f'<div style="max-height: {height}px; overflow: auto; border: 1px solid #ccc;">'
                 f'{df.to_html()}</div>'))

In [5]:
# Sets pandas options that shows all columns in a large dataframe
pd.set_option('display.max_columns', None)

The Data Cleaning functions in the src file are:

- standardize_col_names(df)

Standardizes column names of a dataframe. It will remove white space, replace spaces with underscores, and eliminate special characters (including parenthesis and slashes). All letters are converted to lowercase.

Returns a copy of the dataframe.

- null_counts(df)

Returns a dataframe containing the number of null values in each column of a given dataframe.

### Data
Read in the data and take an initial look.

In [6]:
input_loc = '../data/raw/'

In [7]:
# Loads train_identity.csv into a dataframe, standardizes the column names, and looks at the first 5 rows
df_train_identity = pd.read_csv(input_loc + 'train_identity.csv', dtype={'value':str})
df_train_identity = standardize_col_names(df_train_identity)
df_train_identity.head()

transactionid variable value
0        2987004    id_01   0.0
1        2987008    id_01  -5.0
2        2987010    id_01  -5.0
3        2987011    id_01  -5.0
4        2987016    id_01   0.0

In [8]:
# Looks at the last 10 rows of df_train_identity
df_train_identity.tail(10)

transactionid    variable                               value
5769310        3577495  DeviceInfo                             Windows
5769311        3577499  DeviceInfo                             Windows
5769312        3577501  DeviceInfo                             Windows
5769313        3577506  DeviceInfo                         Trident/7.0
5769314        3577509  DeviceInfo               SM-G930F Build/NRD90M
5769315        3577521  DeviceInfo             F3111 Build/33.3.A.1.97
5769316        3577526  DeviceInfo                 A574BL Build/NMF26F
5769317        3577529  DeviceInfo  Moto E (4) Plus Build/NMA26.42-152
5769318        3577531  DeviceInfo                               MacOS
5769319        3577534  DeviceInfo         RNE-L03 Build/HUAWEIRNE-L03

In [9]:
# Checks out the value counts of the transactionid column in df_train_identity
df_train_identity['transactionid'].value_counts()

transactionid
3577534    40
2987004    40
2987008    40
2987010    40
2987011    40
           ..
2987069    40
2987066    40
2987057    40
2987049    40
2987048    40
Name: count, Length: 144233, dtype: int64

In [10]:
# Checks out the value counts of the variable column in df_train_identity
df_train_identity['variable'].value_counts()

variable
id_01         144233
id_02         144233
id_03         144233
id_04         144233
id_05         144233
id_06         144233
id_07         144233
id_08         144233
id_09         144233
id_10         144233
id_11         144233
id_12         144233
id_13         144233
id_14         144233
id_15         144233
id_16         144233
id_17         144233
id_18         144233
id_19         144233
id_20         144233
id_21         144233
id_22         144233
id_23         144233
id_24         144233
id_25         144233
id_26         144233
id_27         144233
id_28         144233
id_29         144233
id_30         144233
id_31         144233
id_32         144233
id_33         144233
id_34         144233
id_35         144233
id_36         144233
id_37         144233
id_38         144233
DeviceType    144233
DeviceInfo    144233
Name: count, dtype: int64

In [11]:
# Checks out the value counts of the value column in df_train_identity
df_train_identity['value'].value_counts()

value
0.0                     477390
Found                   311573
F                       301692
T                       262248
NotFound                252107
                         ...  
LG-K212                      1
G630-U251                    1
G8142                        1
SM-A520F Build/R16NW         1
149347.0                     1
Name: count, Length: 118675, dtype: int64

In [12]:
# Filters df_train_identity on a single transactionid
df_train_identity_single_transid = df_train_identity[df_train_identity['transactionid']==3577534]
display_scrollable_df(df_train_identity_single_transid)

In [13]:
# Runs the null_counts function on df_train_identity
null_counts(df_train_identity)

null_count  null_fraction
value             2104107       0.364706
transactionid           0       0.000000
variable                0       0.000000

In [14]:
# Loads test_identity.csv into a dataframe, standardizes the column names, and looks at the first 5 rows
df_test_identity = pd.read_csv(input_loc + 'test_identity.csv', dtype={'value':str})
df_test_identity = standardize_col_names(df_test_identity)
df_test_identity.head()

transactionid variable  value
0        3663586    id_01  -45.0
1        3663588    id_01    0.0
2        3663597    id_01   -5.0
3        3663601    id_01  -45.0
4        3663602    id_01  -95.0

In [15]:
# Looks at last 10 rows of df_test_identity
df_test_identity.tail(10)

transactionid    variable                        value
5676270        4170224  DeviceInfo                          NaN
5676271        4170225  DeviceInfo                      Windows
5676272        4170226  DeviceInfo                      LG-M250
5676273        4170228  DeviceInfo              Moto G (5) Plus
5676274        4170229  DeviceInfo                          NaN
5676275        4170230  DeviceInfo                     SM-J700M
5676276        4170233  DeviceInfo                     SM-J320M
5676277        4170234  DeviceInfo                   iOS Device
5676278        4170236  DeviceInfo  ALE-L23 Build/HuaweiALE-L23
5676279        4170239  DeviceInfo                      SAMSUNG

In [16]:
# Checks out the value counts of the transactionid column in df_test_indentity
df_test_identity['transactionid'].value_counts()

transactionid
4170239    40
3663586    40
3663588    40
4170187    40
4170185    40
           ..
3663626    40
3663624    40
3663622    40
3663602    40
3663601    40
Name: count, Length: 141907, dtype: int64

In [17]:
# Filters df_test_identity on a single transactionid
df_test_identity_single_transid = df_test_identity[df_test_identity['transactionid']==4170239]
display_scrollable_df(df_test_identity_single_transid)

In [18]:
# Runs the null_counts function on df_test_identity
null_counts(df_test_identity)

null_count  null_fraction
value             2105385       0.370909
transactionid           0       0.000000
variable                0       0.000000

In [19]:
# Loads train_transaction.csv into a dataframe, standardizes the column names, and looks at the first 5 rows
df_train_transaction = pd.read_csv(input_loc + 'train_transaction.csv')
df_train_transaction = standardize_col_names(df_train_transaction)
df_train_transaction.head()

transactionid  isfraud  transactiondt  transactionamt productcd  card1  \
0        2987000        0          86400            68.5         W  13926   
1        2987001        0          86401            29.0         W   2755   
2        2987002        0          86469            59.0         W   4663   
3        2987003        0          86499            50.0         W  18132   
4        2987004        0          86506            50.0         H   4497   

   card2  card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
0    NaN  150.0    discover  142.0  credit  315.0   87.0   19.0    NaN   
1  404.0  150.0  mastercard  102.0  credit  325.0   87.0    NaN    NaN   
2  490.0  150.0        visa  166.0   debit  330.0   87.0  287.0    NaN   
3  567.0  150.0  mastercard  117.0   debit  476.0   87.0    NaN    NaN   
4  514.0  150.0  mastercard  102.0  credit  420.0   87.0    NaN    NaN   

  p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8   c9  \
0           NaN           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
1     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
2   outlook.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
3     yahoo.com           NaN  2.0  5.0  0.0  0.0  0.0  4.0  0.0  0.0  1.0   
4     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   

   c10  c11  c12   c13  c14     d1     d2    d3    d4   d5  d6  d7  d8  d9  \
0  0.0  2.0  0.0   1.0  1.0   14.0    NaN  13.0   NaN  NaN NaN NaN NaN NaN   
1  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
2  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
3  0.0  1.0  0.0  25.0  1.0  112.0  112.0   0.0  94.0  0.0 NaN NaN NaN NaN   
4  1.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   NaN  NaN NaN NaN NaN NaN   

    d10    d11  d12  d13  d14    d15   m1   m2   m3   m4   m5   m6   m7   m8  \
0  13.0   13.0  NaN  NaN  NaN    0.0    T    T    T   M2    F    T  NaN  NaN   
1   0.0    NaN  NaN  NaN  NaN    0.0  NaN  NaN  NaN   M0    T    T  NaN  NaN   
2   0.0  315.0  NaN  NaN  NaN  315.0    T    T    T   M0    F    F    F    F   
3  84.0    NaN  NaN  NaN  NaN  111.0  NaN  NaN  NaN   M0    T    F  NaN  NaN   
4   NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    m9   v1   v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  \
0  NaN  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0   
2    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0   
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v13  v14  v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  \
0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
3  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v42  v43  v44  v45  v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  \
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0   
1  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

In [20]:
# Looks at the last 5 rows of df_train_transaction
df_train_transaction.tail()

transactionid  isfraud  transactiondt  transactionamt productcd  \
590535        3577535        0       15811047           49.00         W   
590536        3577536        0       15811049           39.50         W   
590537        3577537        0       15811079           30.95         W   
590538        3577538        0       15811088          117.00         W   
590539        3577539        0       15811131          279.95         W   

        card1  card2  card3       card4  card5   card6  addr1  addr2  dist1  \
590535   6550    NaN  150.0        visa  226.0   debit  272.0   87.0   48.0   
590536  10444  225.0  150.0  mastercard  224.0   debit  204.0   87.0    NaN   
590537  12037  595.0  150.0  mastercard  224.0   debit  231.0   87.0    NaN   
590538   7826  481.0  150.0  mastercard  224.0   debit  387.0   87.0    3.0   
590539  15066  170.0  150.0  mastercard  102.0  credit  299.0   87.0    NaN   

        dist2 p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7  \
590535    NaN           NaN           NaN  2.0  1.0  0.0  0.0  1.0  0.0  0.0   
590536    NaN     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0   
590537    NaN     gmail.com           NaN  1.0  1.0  0.0  0.0  1.0  1.0  0.0   
590538    NaN       aol.com           NaN  1.0  1.0  0.0  0.0  0.0  3.0  0.0   
590539    NaN     gmail.com           NaN  2.0  1.0  0.0  0.0  1.0  1.0  0.0   

         c8   c9  c10  c11  c12  c13  c14    d1    d2    d3    d4   d5  d6  \
590535  0.0  2.0  0.0  1.0  0.0  3.0  2.0  29.0  29.0  30.0   NaN  NaN NaN   
590536  0.0  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0  NaN NaN   
590537  0.0  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0  NaN NaN   
590538  0.0  2.0  0.0  1.0  1.0  5.0  1.0  22.0  22.0   0.0  22.0  0.0 NaN   
590539  0.0  2.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   0.0   1.0  0.0 NaN   

        d7  d8  d9   d10   d11  d12  d13  d14   d15 m1 m2 m3   m4   m5 m6  \
590535 NaN NaN NaN  56.0  56.0  NaN  NaN  NaN  56.0  T  T  T   M0    T  F   
590536 NaN NaN NaN   0.0   0.0  NaN  NaN  NaN   0.0  T  F  F   M0    F  T   
590537 NaN NaN NaN   0.0   0.0  NaN  NaN  NaN   0.0  T  F  F  NaN  NaN  T   
590538 NaN NaN NaN  22.0  22.0  NaN  NaN  NaN  22.0  T  T  T   M0    F  T   
590539 NaN NaN NaN   1.0   0.0  NaN  NaN  NaN   1.0  T  F  F  NaN  NaN  T   

         m7   m8   m9   v1   v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  \
590535    F    F    T  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
590536    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0   
590537  NaN  NaN  NaN  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
590538  NaN  NaN  NaN  1.0  1.0  1.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  0.0   
590539    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   

        v11  v12  v12  v13  v14  v15  v16  v17  v18  v19  v20  v21  v22  v23  \
590535  0.0  2.0  2.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
590536  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0   
590537  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0   
590538  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  2.0  2.0  0.0  0.0  1.0   
590539  1.0  2.0  2.0  2.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0   

        v24  v25  v26  v27  v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  \
590535  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN   
590536  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
590537  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
590538  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   
590539  2.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  2.0  2.0  1.0   

        v38  v39  v40  v41  v42  v42  v43  v44  v45  v46  v47  v48  v49  v50  \
590535  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
590536  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0

In [21]:
# Checks out the value counts of the transactionid column in df_train_transaction and sorts the values in descending order
df_train_transaction['transactionid'].value_counts().sort_values(ascending=False)

transactionid
2987012    1
3577539    1
2987000    1
2987001    1
2987002    1
          ..
3577519    1
3577520    1
3577521    1
3577522    1
3577523    1
Name: count, Length: 590540, dtype: int64

In [22]:
# Runs the null_counts function on df_train_transaction
null_counts(df_train_transaction)

null_count  null_fraction
v340               590540       1.000000
dist2              552913       0.936284
d7                 551623       0.934099
d13                528588       0.895093
d14                528353       0.894695
...                   ...            ...
c3                      0       0.000000
c4                      0       0.000000
c5                      0       0.000000
c2                      0       0.000000
transactionid           0       0.000000

[403 rows x 2 columns]

In [23]:
# Loads test_transaction.csv into a dataframe, standardizes the column names, and looks at the first 5 rows
df_test_transaction = pd.read_csv(input_loc + 'test_transaction.csv')
df_test_transaction = standardize_col_names(df_test_transaction)
df_test_transaction.head()

transactionid  transactiondt  transactionamt productcd  card1  card2  \
0        3663549       18403224           31.95         W  10409  111.0   
1        3663550       18403263           49.00         W   4272  111.0   
2        3663551       18403310          171.00         W   4476  574.0   
3        3663552       18403310          284.95         W  10989  360.0   
4        3663553       18403317           67.95         W  18018  452.0   

   card3       card4  card5  card6  addr1  addr2   dist1  dist2 p_emaildomain  \
0  150.0        visa  226.0  debit  170.0   87.0     1.0    NaN     gmail.com   
1  150.0        visa  226.0  debit  299.0   87.0     4.0    NaN       aol.com   
2  150.0        visa  226.0  debit  472.0   87.0  2635.0    NaN   hotmail.com   
3  150.0        visa  166.0  debit  205.0   87.0    17.0    NaN     gmail.com   
4  150.0  mastercard  117.0  debit  264.0   87.0     6.0    NaN     gmail.com   

  r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  c12  \
0           NaN  6.0  6.0  0.0  0.0  3.0  4.0  0.0  0.0  6.0  0.0  5.0  1.0   
1           NaN  3.0  2.0  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  1.0  1.0   
2           NaN  2.0  2.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0  0.0  2.0  0.0   
3           NaN  5.0  2.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  0.0  2.0  0.0   
4           NaN  6.0  6.0  0.0  0.0  2.0  5.0  0.0  0.0  5.0  0.0  6.0  0.0   

     c13  c14     d1     d2    d3     d4    d5  d6  d7  d8  d9    d10    d11  \
0  115.0  6.0  419.0  419.0  27.0  398.0  27.0 NaN NaN NaN NaN  418.0  203.0   
1   12.0  2.0  149.0  149.0   7.0  634.0   7.0 NaN NaN NaN NaN  231.0  634.0   
2   22.0  2.0  137.0  137.0  10.0   97.0  10.0 NaN NaN NaN NaN  136.0  136.0   
3    7.0  4.0   42.0   42.0  41.0  242.0  41.0 NaN NaN NaN NaN  242.0  242.0   
4   14.0  6.0   22.0   22.0   0.0   22.0   0.0 NaN NaN NaN NaN   22.0   22.0   

   d12  d13  d14    d15 m1 m2 m3   m4   m5 m6   m7   m8   m9   v1   v2   v3  \
0  NaN  NaN  NaN  409.0  T  T  F  NaN  NaN  F    T    T    T  1.0  1.0  1.0   
1  NaN  NaN  NaN  634.0  T  F  F   M0  NaN  F  NaN  NaN  NaN  1.0  1.0  1.0   
2  NaN  NaN  NaN   97.0  T  T  F   M0    F  F    F    F    F  1.0  1.0  1.0   
3  NaN  NaN  NaN  242.0  T  T  T  NaN  NaN  T  NaN  NaN  NaN  1.0  1.0  1.0   
4  NaN  NaN  NaN   22.0  T  T  T  NaN  NaN  F    F    T    T  1.0  1.0  1.0   

    v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  v16  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   

   v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  v30  v31  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  1.0  1.0  0.0  0.0  2.0  2.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0   
4  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0   

   v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  v44  v45  \
0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
1  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
2  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
3  0.0  0.0  0.0  2.0  2.0  2.0  2.0  0.0  0.0  1.0  0.0  0.0  0.0  2.0  2.0   
4  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   

   v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  v57  v58  v59  v60  \
0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   
1  1.0  1.0  0.0  0.0  0.0  0.0

In [24]:
# Looks at the last 5 rows of df_test_transaction
df_test_transaction.tail()

transactionid  transactiondt  transactionamt productcd  card1  card2  \
506686        4170235       34214279          94.679         C  13832  375.0   
506687        4170236       34214287          12.173         C   3154  408.0   
506688        4170237       34214326          49.000         W  16661  490.0   
506689        4170238       34214337         202.000         W  16621  516.0   
506690        4170239       34214345          24.346         C   5713  168.0   

        card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
506686  185.0  mastercard  224.0   debit  284.0   60.0    NaN    NaN   
506687  185.0  mastercard  224.0   debit    NaN    NaN    NaN  157.0   
506688  150.0        visa  226.0   debit  327.0   87.0    NaN    NaN   
506689  150.0  mastercard  224.0   debit  177.0   87.0    NaN    NaN   
506690  144.0        visa  147.0  credit    NaN    NaN    NaN    NaN   

       p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8  \
506686     gmail.com     gmail.com  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0   
506687   hotmail.com   hotmail.com  1.0  3.0  0.0  1.0  0.0  1.0  1.0  2.0   
506688   hotmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
506689   hotmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
506690   hotmail.com   hotmail.com  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0   

         c9  c10  c11  c12  c13  c14    d1    d2    d3    d4    d5    d6  \
506686  0.0  0.0  1.0  1.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   0.0   
506687  0.0  2.0  1.0  1.0  3.0  1.0  16.0  16.0  16.0  16.0  16.0  16.0   
506688  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   NaN   
506689  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   NaN   
506690  0.0  1.0  1.0  1.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   0.0   

          d7         d8        d9  d10  d11   d12  d13  d14   d15   m1   m2  \
506686   NaN        NaN       NaN  0.0  NaN   0.0  NaN  NaN   0.0  NaN  NaN   
506687  16.0        NaN       NaN  0.0  NaN  16.0  0.0  0.0  16.0  NaN  NaN   
506688   NaN        NaN       NaN  0.0  0.0   NaN  NaN  NaN   0.0    T    T   
506689   NaN        NaN       NaN  0.0  0.0   NaN  NaN  NaN   0.0    T    T   
506690   NaN  29.958332  0.958333  0.0  NaN   0.0  0.0  0.0   0.0  NaN  NaN   

         m3  m4   m5   m6   m7   m8   m9   v1   v2   v3   v4   v5   v5   v6  \
506686  NaN  M2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
506687  NaN  M2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
506688    T  M0    F    F    F    T    T  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
506689    T  M0    F    F    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
506690  NaN  M2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

         v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  v16  v17  v18  v19  \
506686  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  1.0   
506687  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0   
506688  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0   
506689  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0   
506690  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0   

        v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  v30  v31  v32  v33  \
506686  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
506687  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
506688  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
506689  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
506690  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   

        v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  v44  v45  v46  \
506686  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0   
506687  1.0  0.0  0.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
506688  0.0  1.0

In [25]:
# Checks out the value counts of the transactionid column in df_test_transaction and sorts them in descending order
df_test_transaction['transactionid'].value_counts().sort_values(ascending=False)

transactionid
3663552    1
4170239    1
3663549    1
4170224    1
4170225    1
          ..
4170219    1
4170220    1
4170221    1
4170222    1
4170223    1
Name: count, Length: 506691, dtype: int64

In [26]:
# Runs the null_counts function on df_test_transaction
null_counts(df_test_transaction)

null_count  null_fraction
v340               506691       1.000000
dist2              470255       0.928090
d7                 446558       0.881322
d12                437437       0.863321
d8                 432353       0.853287
...                   ...            ...
v99                     0       0.000000
v100                    0       0.000000
v101                    0       0.000000
v102                    0       0.000000
transactionid           0       0.000000

[402 rows x 2 columns]

## Describing the Data
Before diving into the data, let's consider a few practical issues, which may or may not be important, depending on your dataset.

### Data Shape
Take a look at the current shape of the data set or sets. Is it in a convenient form to perform some exploratory analysis on? If not, what will you need to change before analysis can happen?

In [27]:
# Looks at the shape of df_train_identity
df_train_identity.shape

(5769320, 3)

In [28]:
# Looks at the shape of df_test_identity
df_test_identity.shape

(5676280, 3)

- train_identity.csv is not ready for exploratory data analysis and test_identity.csv is not ready for testing, as both tables need to be reshaped first
- The variable and value columns in the identity datasets are oriented incorrectly. This became apparent when I looked at the value counts of the transactionid and variable columns, and then filtered the df_train_identity dataframe on a single transactionid
- When I looked at the value counts of the transactionid and variable columns in train_identity.csv, I saw that there are 144,233 unique transactionids each of which has a count of 40, while there are 40 unique values in the variable column, each of which has a count of 144,233
- When I filtered the dataframe on a single transactionid, I saw that the variable column is a column of variables and the value column is a column of values. Each variable in the variable column should be a column header, with the corresponding value in their row as a value in their column
- When both dataframes are reshaped, each transactionid should have one row, not 40, with all the values that appear in the value column when you filter the current dataframe on that transaction id, and every value of the variable column should be the header.
- When df_train_identity is reshaped, it will have the shape (144233, 41)
- When df_test_identity is reshaped, it will have the shape (141907, 41)

In [29]:
# Looks at the shape of df_train_identity
df_train_identity_single_transid_2 = df_train_identity[df_train_identity['transactionid']==3577534]
display_scrollable_df(df_train_identity_single_transid_2)

In [30]:
# Looks at the shape of df_train_transaction
df_train_transaction.shape

(590540, 403)

In [31]:
# Looks at the shape of df_test_transaction
df_test_transaction.shape

(506691, 402)

- train_transaction.csv is not very convenient for exploratory analysis and test_transaction.csv is not very convenient for testing, as both files contain so many variables, many of which have missing values
- To correct this before analysis happens, I need to determine if the variables with many missing values can be dropped, drop them if it makes sense, and see if the remaining number of variables is more manageable 

### Data Type
Which data types does each variable contain? Are variables continuous or categorical?
- Because the identity dataframes need to be reshaped, I'll revisit this question later in the notebook. For now, I will call the info method off each dataframe to see the datatypes present at the moment

In [32]:
# Calls the info method off df_train_identity
df_train_identity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5769320 entries, 0 to 5769319
Data columns (total 3 columns):
 #   Column         Dtype 
---  ------         ----- 
 0   transactionid  int64 
 1   variable       object
 2   value          object
dtypes: int64(1), object(2)
memory usage: 132.0+ MB


In [33]:
# Calls the info method off df_test_identity
df_test_identity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5676280 entries, 0 to 5676279
Data columns (total 3 columns):
 #   Column         Dtype 
---  ------         ----- 
 0   transactionid  int64 
 1   variable       object
 2   value          object
dtypes: int64(1), object(2)
memory usage: 129.9+ MB


In [34]:
# Calls the info method off df_train_transaction
df_train_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 403 entries, transactionid to v340
dtypes: float64(385), int64(4), object(14)
memory usage: 1.8+ GB


In [35]:
# Calls the info method off df_test_transaction
df_test_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506691 entries, 0 to 506690
Columns: 402 entries, transactionid to v340
dtypes: float64(385), int64(3), object(14)
memory usage: 1.5+ GB


### Data Amount
How much data does the set contain? (ie, how many variables, how many records, how many files?) If the data set is very large, this may effect the tools you can use later (or else how much features selection will need to take place).

- There are 4 datasets in the raw folder relevant to analysis - train_identity.csv, test_identity.csv, train_transaction.csv, test_transaction.csv
- train_identity.csv has 5,769,320 rows of data and 3 variables
- After reshaping train_identity.csv, the resulting dataframe will have 144,230 rows of data and 41 variables
- test_identity.csv has 5,676,280 rows of data and 3 variables
- After reshaping test_identity.csv, the resulting dataframe will have 141,907 rows of data and 41 variables
- train_transaction.csv has 590,540 rows of data and 403 variables
- test_transaction.csv has 506,691 rows of data and 402 variables

## Cleaning

Before you can dive into exploratory analysis, it's likely that you will have to do some reshaping of the data. Depending on what your data set looks like, there may be a lot or very little work to do here.

### Combine and/or Reshape
Be careful not to lose any data while reshaping. Make sure you have the same number of variables and observations in the raw set as you do after reshaping. Keep in mind that, for analysis and machine learning, you will want to have one or more dataframes with each column representing a measured variable and each row representing an observation.

#### Reshaping df_train_identity and df_test_identity

In [36]:
# Tests reshaping df_train_identity filtered on one transactionid
one_id = df_train_identity[df_train_identity['transactionid']==3577534].pivot(index='transactionid', columns='variable', values='value').reset_index().rename_axis(None, axis=1)
one_id

transactionid                   DeviceInfo DeviceType  id_01     id_02  \
0        3577534  RNE-L03 Build/HUAWEIRNE-L03     mobile  -45.0  339406.0   

  id_03 id_04  id_05   id_06 id_07 id_08 id_09 id_10  id_11     id_12 id_13  \
0   NaN   NaN  -10.0  -100.0   NaN   NaN   NaN   NaN  100.0  NotFound  27.0   

  id_14 id_15     id_16  id_17 id_18  id_19  id_20 id_21 id_22 id_23 id_24  \
0   NaN   New  NotFound  225.0  15.0  417.0  595.0   NaN   NaN   NaN   NaN   

  id_25 id_26 id_27 id_28     id_29 id_30                    id_31 id_32  \
0   NaN   NaN   NaN   New  NotFound   NaN  chrome 66.0 for android   NaN   

  id_33 id_34 id_35 id_36 id_37 id_38  
0   NaN   NaN     F     F     T     F

In [37]:
# Reshapes df_train_identity and takes a look at the first five rows
df_train_identity_reshaped = df_train_identity.pivot(index='transactionid', columns='variable', values='value').reset_index().rename_axis(None, axis=1)
df_train_identity_reshaped.head()

transactionid                     DeviceInfo DeviceType id_01     id_02  \
0        2987004  SAMSUNG SM-G892A Build/NRD90M     mobile   0.0   70787.0   
1        2987008                     iOS Device     mobile  -5.0   98945.0   
2        2987010                        Windows    desktop  -5.0  191631.0   
3        2987011                            NaN    desktop  -5.0  221832.0   
4        2987016                          MacOS    desktop   0.0    7460.0   

  id_03 id_04 id_05 id_06 id_07 id_08 id_09 id_10  id_11     id_12 id_13  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  100.0  NotFound   NaN   
1   NaN   NaN   0.0  -5.0   NaN   NaN   NaN   NaN  100.0  NotFound  49.0   
2   0.0   0.0   0.0   0.0   NaN   NaN   0.0   0.0  100.0  NotFound  52.0   
3   NaN   NaN   0.0  -6.0   NaN   NaN   NaN   NaN  100.0  NotFound  52.0   
4   0.0   0.0   1.0   0.0   NaN   NaN   0.0   0.0  100.0  NotFound   NaN   

    id_14  id_15     id_16  id_17 id_18  id_19  id_20 id_21 id_22 id_23 id_24  \
0  -480.0    New  NotFound  166.0   NaN  542.0  144.0   NaN   NaN   NaN   NaN   
1  -300.0    New  NotFound  166.0   NaN  621.0  500.0   NaN   NaN   NaN   NaN   
2     NaN  Found     Found  121.0   NaN  410.0  142.0   NaN   NaN   NaN   NaN   
3     NaN    New  NotFound  225.0   NaN  176.0  507.0   NaN   NaN   NaN   NaN   
4  -300.0  Found     Found  166.0  15.0  529.0  575.0   NaN   NaN   NaN   NaN   

  id_25 id_26 id_27  id_28     id_29             id_30                id_31  \
0   NaN   NaN   NaN    New  NotFound       Android 7.0  samsung browser 6.2   
1   NaN   NaN   NaN    New  NotFound        iOS 11.1.2   mobile safari 11.0   
2   NaN   NaN   NaN  Found     Found               NaN          chrome 62.0   
3   NaN   NaN   NaN    New  NotFound               NaN          chrome 62.0   
4   NaN   NaN   NaN  Found     Found  Mac OS X 10_11_6          chrome 62.0   

  id_32      id_33           id_34 id_35 id_36 id_37 id_38  
0  32.0  2220x1080  match_status:2     T     F     T     T  
1  32.0   1334x750  match_status:1     T     F     F     T  
2   NaN        NaN             NaN     F     F     T     T  
3   NaN        NaN             NaN     F     F     T     T  
4  24.0   1280x800  match_status:2     T     F     T     T

In [38]:
# Looks at shape of df_train_identity_reshaped
df_train_identity_reshaped.shape

(144233, 41)

In [39]:
# Calls info method off df_train_identity_reshaped
df_train_identity_reshaped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144233 entries, 0 to 144232
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype 
---  ------         --------------   ----- 
 0   transactionid  144233 non-null  int64 
 1   DeviceInfo     118666 non-null  object
 2   DeviceType     140810 non-null  object
 3   id_01          144233 non-null  object
 4   id_02          140872 non-null  object
 5   id_03          66324 non-null   object
 6   id_04          66324 non-null   object
 7   id_05          136865 non-null  object
 8   id_06          136865 non-null  object
 9   id_07          5155 non-null    object
 10  id_08          5155 non-null    object
 11  id_09          74926 non-null   object
 12  id_10          74926 non-null   object
 13  id_11          140978 non-null  object
 14  id_12          144233 non-null  object
 15  id_13          127320 non-null  object
 16  id_14          80044 non-null   object
 17  id_15          140985 non-null  object
 18  id_1

In [40]:
# Reshapes df_test_identity and looks at the first five rows
df_test_identity_reshaped = df_test_identity.pivot(index='transactionid', columns='variable', values='value').reset_index().rename_axis(None, axis=1)
df_test_identity_reshaped.head()

transactionid                   DeviceInfo DeviceType  id_01     id_02  \
0        3663586  MYA-L13 Build/HUAWEIMYA-L13     mobile  -45.0  280290.0   
1        3663588         LGLS676 Build/MXB48T     mobile    0.0    3579.0   
2        3663597                  Trident/7.0    desktop   -5.0  185210.0   
3        3663601  MYA-L13 Build/HUAWEIMYA-L13     mobile  -45.0  252944.0   
4        3663602         SM-G9650 Build/R16NW     mobile  -95.0  328680.0   

  id_03 id_04 id_05  id_06 id_07 id_08 id_09 id_10  id_11     id_12 id_13  \
0   NaN   NaN   0.0    0.0   NaN   NaN   NaN   NaN  100.0  NotFound  27.0   
1   0.0   0.0   0.0    0.0   NaN   NaN   0.0   0.0  100.0     Found   NaN   
2   NaN   NaN   1.0    0.0   NaN   NaN   NaN   NaN  100.0  NotFound  52.0   
3   0.0   0.0   0.0    0.0   NaN   NaN   0.0   0.0  100.0  NotFound  27.0   
4   NaN   NaN   7.0  -33.0   NaN   NaN   NaN   NaN  100.0  NotFound  27.0   

    id_14  id_15     id_16  id_17 id_18  id_19  id_20 id_21 id_22 id_23 id_24  \
0     NaN    New  NotFound  225.0  15.0  427.0  563.0   NaN   NaN   NaN   NaN   
1  -300.0  Found     Found  166.0   NaN  542.0  368.0   NaN   NaN   NaN   NaN   
2  -360.0    New  NotFound  225.0   NaN  271.0  507.0   NaN   NaN   NaN   NaN   
3     NaN  Found     Found  225.0  15.0  427.0  563.0   NaN   NaN   NaN   NaN   
4     NaN    New  NotFound  225.0  15.0  567.0  507.0   NaN   NaN   NaN   NaN   

  id_25 id_26 id_27  id_28     id_29          id_30                    id_31  \
0   NaN   NaN   NaN    New  NotFound            NaN  chrome 67.0 for android   
1   NaN   NaN   NaN  Found     Found  Android 6.0.1  chrome 67.0 for android   
2   NaN   NaN   NaN    New  NotFound            NaN       ie 11.0 for tablet   
3   NaN   NaN   NaN  Found     Found            NaN  chrome 67.0 for android   
4   NaN   NaN   NaN    New  NotFound            NaN  chrome 67.0 for android   

  id_32     id_33           id_34 id_35 id_36 id_37 id_38  
0   NaN       NaN             NaN     F     F     T     F  
1  24.0  1280x720  match_status:2     T     F     T     T  
2   NaN       NaN             NaN     F     T     T     F  
3   NaN       NaN             NaN     F     F     T     F  
4   NaN       NaN             NaN     F     F     T     F

In [41]:
# Looks at shape of df_test_identity_reshaped
df_test_identity_reshaped.shape

(141907, 41)

In [42]:
# Calls info method off df_test_identity_reshaped
df_test_identity_reshaped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141907 entries, 0 to 141906
Data columns (total 41 columns):
 #   Column         Non-Null Count   Dtype 
---  ------         --------------   ----- 
 0   transactionid  141907 non-null  int64 
 1   DeviceInfo     115057 non-null  object
 2   DeviceType     136931 non-null  object
 3   id_01          141907 non-null  object
 4   id_02          136976 non-null  object
 5   id_03          66481 non-null   object
 6   id_04          66481 non-null   object
 7   id_05          134750 non-null  object
 8   id_06          134750 non-null  object
 9   id_07          5059 non-null    object
 10  id_08          5059 non-null    object
 11  id_09          74338 non-null   object
 12  id_10          74338 non-null   object
 13  id_11          136778 non-null  object
 14  id_12          141907 non-null  object
 15  id_13          130286 non-null  object
 16  id_14          71357 non-null   object
 17  id_15          136977 non-null  object
 18  id_1

#### Merging df_train_transaction with df_train_identity_reshaped and df_test_transaction with df_test_identity_reshaped

In [43]:
# Merges df_train_transaction and df_train_identity_reshaped on transactionid column using left join
df_train = pd.merge(df_train_transaction, df_train_identity_reshaped, on='transactionid', how='left')

In [44]:
# Looks at first 5 rows of df_train
df_train.head()

transactionid  isfraud  transactiondt  transactionamt productcd  card1  \
0        2987000        0          86400            68.5         W  13926   
1        2987001        0          86401            29.0         W   2755   
2        2987002        0          86469            59.0         W   4663   
3        2987003        0          86499            50.0         W  18132   
4        2987004        0          86506            50.0         H   4497   

   card2  card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
0    NaN  150.0    discover  142.0  credit  315.0   87.0   19.0    NaN   
1  404.0  150.0  mastercard  102.0  credit  325.0   87.0    NaN    NaN   
2  490.0  150.0        visa  166.0   debit  330.0   87.0  287.0    NaN   
3  567.0  150.0  mastercard  117.0   debit  476.0   87.0    NaN    NaN   
4  514.0  150.0  mastercard  102.0  credit  420.0   87.0    NaN    NaN   

  p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8   c9  \
0           NaN           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
1     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
2   outlook.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
3     yahoo.com           NaN  2.0  5.0  0.0  0.0  0.0  4.0  0.0  0.0  1.0   
4     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   

   c10  c11  c12   c13  c14     d1     d2    d3    d4   d5  d6  d7  d8  d9  \
0  0.0  2.0  0.0   1.0  1.0   14.0    NaN  13.0   NaN  NaN NaN NaN NaN NaN   
1  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
2  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
3  0.0  1.0  0.0  25.0  1.0  112.0  112.0   0.0  94.0  0.0 NaN NaN NaN NaN   
4  1.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   NaN  NaN NaN NaN NaN NaN   

    d10    d11  d12  d13  d14    d15   m1   m2   m3   m4   m5   m6   m7   m8  \
0  13.0   13.0  NaN  NaN  NaN    0.0    T    T    T   M2    F    T  NaN  NaN   
1   0.0    NaN  NaN  NaN  NaN    0.0  NaN  NaN  NaN   M0    T    T  NaN  NaN   
2   0.0  315.0  NaN  NaN  NaN  315.0    T    T    T   M0    F    F    F    F   
3  84.0    NaN  NaN  NaN  NaN  111.0  NaN  NaN  NaN   M0    T    F  NaN  NaN   
4   NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    m9   v1   v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  \
0  NaN  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0   
2    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0   
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v13  v14  v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  \
0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
3  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v42  v43  v44  v45  v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  \
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0   
1  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

In [45]:
# Looks at last 20 rows of df_train
df_train.tail()

transactionid  isfraud  transactiondt  transactionamt productcd  \
590535        3577535        0       15811047           49.00         W   
590536        3577536        0       15811049           39.50         W   
590537        3577537        0       15811079           30.95         W   
590538        3577538        0       15811088          117.00         W   
590539        3577539        0       15811131          279.95         W   

        card1  card2  card3       card4  card5   card6  addr1  addr2  dist1  \
590535   6550    NaN  150.0        visa  226.0   debit  272.0   87.0   48.0   
590536  10444  225.0  150.0  mastercard  224.0   debit  204.0   87.0    NaN   
590537  12037  595.0  150.0  mastercard  224.0   debit  231.0   87.0    NaN   
590538   7826  481.0  150.0  mastercard  224.0   debit  387.0   87.0    3.0   
590539  15066  170.0  150.0  mastercard  102.0  credit  299.0   87.0    NaN   

        dist2 p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7  \
590535    NaN           NaN           NaN  2.0  1.0  0.0  0.0  1.0  0.0  0.0   
590536    NaN     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0   
590537    NaN     gmail.com           NaN  1.0  1.0  0.0  0.0  1.0  1.0  0.0   
590538    NaN       aol.com           NaN  1.0  1.0  0.0  0.0  0.0  3.0  0.0   
590539    NaN     gmail.com           NaN  2.0  1.0  0.0  0.0  1.0  1.0  0.0   

         c8   c9  c10  c11  c12  c13  c14    d1    d2    d3    d4   d5  d6  \
590535  0.0  2.0  0.0  1.0  0.0  3.0  2.0  29.0  29.0  30.0   NaN  NaN NaN   
590536  0.0  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0  NaN NaN   
590537  0.0  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0  NaN NaN   
590538  0.0  2.0  0.0  1.0  1.0  5.0  1.0  22.0  22.0   0.0  22.0  0.0 NaN   
590539  0.0  2.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   0.0   1.0  0.0 NaN   

        d7  d8  d9   d10   d11  d12  d13  d14   d15 m1 m2 m3   m4   m5 m6  \
590535 NaN NaN NaN  56.0  56.0  NaN  NaN  NaN  56.0  T  T  T   M0    T  F   
590536 NaN NaN NaN   0.0   0.0  NaN  NaN  NaN   0.0  T  F  F   M0    F  T   
590537 NaN NaN NaN   0.0   0.0  NaN  NaN  NaN   0.0  T  F  F  NaN  NaN  T   
590538 NaN NaN NaN  22.0  22.0  NaN  NaN  NaN  22.0  T  T  T   M0    F  T   
590539 NaN NaN NaN   1.0   0.0  NaN  NaN  NaN   1.0  T  F  F  NaN  NaN  T   

         m7   m8   m9   v1   v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  \
590535    F    F    T  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
590536    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0   
590537  NaN  NaN  NaN  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
590538  NaN  NaN  NaN  1.0  1.0  1.0  2.0  2.0  2.0  1.0  1.0  1.0  1.0  0.0   
590539    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   

        v11  v12  v12  v13  v14  v15  v16  v17  v18  v19  v20  v21  v22  v23  \
590535  0.0  2.0  2.0  2.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
590536  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0   
590537  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0   
590538  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  2.0  2.0  0.0  0.0  1.0   
590539  1.0  2.0  2.0  2.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0   

        v24  v25  v26  v27  v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  \
590535  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN   
590536  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
590537  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
590538  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   
590539  2.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  2.0  2.0  1.0   

        v38  v39  v40  v41  v42  v42  v43  v44  v45  v46  v47  v48  v49  v50  \
590535  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
590536  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0

In [46]:
# Looks at shape of df_train
df_train.shape

(590540, 443)

In [47]:
# Calls info method off df_train
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 443 entries, transactionid to id_38
dtypes: float64(385), int64(4), object(54)
memory usage: 1.9+ GB


In [48]:
# Merges df_test_transaction and df_test_identity_reshaped on transactionid column using left join
df_test = pd.merge(df_test_transaction, df_test_identity_reshaped, on='transactionid', how='left')

In [49]:
# Looks at first five rows of df_test
df_test.head()

transactionid  transactiondt  transactionamt productcd  card1  card2  \
0        3663549       18403224           31.95         W  10409  111.0   
1        3663550       18403263           49.00         W   4272  111.0   
2        3663551       18403310          171.00         W   4476  574.0   
3        3663552       18403310          284.95         W  10989  360.0   
4        3663553       18403317           67.95         W  18018  452.0   

   card3       card4  card5  card6  addr1  addr2   dist1  dist2 p_emaildomain  \
0  150.0        visa  226.0  debit  170.0   87.0     1.0    NaN     gmail.com   
1  150.0        visa  226.0  debit  299.0   87.0     4.0    NaN       aol.com   
2  150.0        visa  226.0  debit  472.0   87.0  2635.0    NaN   hotmail.com   
3  150.0        visa  166.0  debit  205.0   87.0    17.0    NaN     gmail.com   
4  150.0  mastercard  117.0  debit  264.0   87.0     6.0    NaN     gmail.com   

  r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  c12  \
0           NaN  6.0  6.0  0.0  0.0  3.0  4.0  0.0  0.0  6.0  0.0  5.0  1.0   
1           NaN  3.0  2.0  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  1.0  1.0   
2           NaN  2.0  2.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0  0.0  2.0  0.0   
3           NaN  5.0  2.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  0.0  2.0  0.0   
4           NaN  6.0  6.0  0.0  0.0  2.0  5.0  0.0  0.0  5.0  0.0  6.0  0.0   

     c13  c14     d1     d2    d3     d4    d5  d6  d7  d8  d9    d10    d11  \
0  115.0  6.0  419.0  419.0  27.0  398.0  27.0 NaN NaN NaN NaN  418.0  203.0   
1   12.0  2.0  149.0  149.0   7.0  634.0   7.0 NaN NaN NaN NaN  231.0  634.0   
2   22.0  2.0  137.0  137.0  10.0   97.0  10.0 NaN NaN NaN NaN  136.0  136.0   
3    7.0  4.0   42.0   42.0  41.0  242.0  41.0 NaN NaN NaN NaN  242.0  242.0   
4   14.0  6.0   22.0   22.0   0.0   22.0   0.0 NaN NaN NaN NaN   22.0   22.0   

   d12  d13  d14    d15 m1 m2 m3   m4   m5 m6   m7   m8   m9   v1   v2   v3  \
0  NaN  NaN  NaN  409.0  T  T  F  NaN  NaN  F    T    T    T  1.0  1.0  1.0   
1  NaN  NaN  NaN  634.0  T  F  F   M0  NaN  F  NaN  NaN  NaN  1.0  1.0  1.0   
2  NaN  NaN  NaN   97.0  T  T  F   M0    F  F    F    F    F  1.0  1.0  1.0   
3  NaN  NaN  NaN  242.0  T  T  T  NaN  NaN  T  NaN  NaN  NaN  1.0  1.0  1.0   
4  NaN  NaN  NaN   22.0  T  T  T  NaN  NaN  F    F    T    T  1.0  1.0  1.0   

    v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  v16  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   

   v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  v30  v31  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  1.0  1.0  0.0  0.0  2.0  2.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0   
4  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0   

   v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  v44  v45  \
0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
1  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
2  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
3  0.0  0.0  0.0  2.0  2.0  2.0  2.0  0.0  0.0  1.0  0.0  0.0  0.0  2.0  2.0   
4  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   

   v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  v57  v58  v59  v60  \
0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   
1  1.0  1.0  0.0  0.0  0.0  0.0

In [50]:
# Looks at last 5 rows of df_test
df_test.tail()

transactionid  transactiondt  transactionamt productcd  card1  card2  \
506686        4170235       34214279          94.679         C  13832  375.0   
506687        4170236       34214287          12.173         C   3154  408.0   
506688        4170237       34214326          49.000         W  16661  490.0   
506689        4170238       34214337         202.000         W  16621  516.0   
506690        4170239       34214345          24.346         C   5713  168.0   

        card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
506686  185.0  mastercard  224.0   debit  284.0   60.0    NaN    NaN   
506687  185.0  mastercard  224.0   debit    NaN    NaN    NaN  157.0   
506688  150.0        visa  226.0   debit  327.0   87.0    NaN    NaN   
506689  150.0  mastercard  224.0   debit  177.0   87.0    NaN    NaN   
506690  144.0        visa  147.0  credit    NaN    NaN    NaN    NaN   

       p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8  \
506686     gmail.com     gmail.com  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0   
506687   hotmail.com   hotmail.com  1.0  3.0  0.0  1.0  0.0  1.0  1.0  2.0   
506688   hotmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
506689   hotmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
506690   hotmail.com   hotmail.com  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0   

         c9  c10  c11  c12  c13  c14    d1    d2    d3    d4    d5    d6  \
506686  0.0  0.0  1.0  1.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   0.0   
506687  0.0  2.0  1.0  1.0  3.0  1.0  16.0  16.0  16.0  16.0  16.0  16.0   
506688  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   NaN   
506689  1.0  0.0  1.0  0.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   NaN   
506690  0.0  1.0  1.0  1.0  1.0  1.0   0.0   NaN   NaN   0.0   NaN   0.0   

          d7         d8        d9  d10  d11   d12  d13  d14   d15   m1   m2  \
506686   NaN        NaN       NaN  0.0  NaN   0.0  NaN  NaN   0.0  NaN  NaN   
506687  16.0        NaN       NaN  0.0  NaN  16.0  0.0  0.0  16.0  NaN  NaN   
506688   NaN        NaN       NaN  0.0  0.0   NaN  NaN  NaN   0.0    T    T   
506689   NaN        NaN       NaN  0.0  0.0   NaN  NaN  NaN   0.0    T    T   
506690   NaN  29.958332  0.958333  0.0  NaN   0.0  0.0  0.0   0.0  NaN  NaN   

         m3  m4   m5   m6   m7   m8   m9   v1   v2   v3   v4   v5   v5   v6  \
506686  NaN  M2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
506687  NaN  M2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
506688    T  M0    F    F    F    T    T  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
506689    T  M0    F    F    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
506690  NaN  M2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

         v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  v16  v17  v18  v19  \
506686  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  1.0   
506687  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0   
506688  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0   
506689  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0   
506690  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0   

        v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  v30  v31  v32  v33  \
506686  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
506687  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
506688  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
506689  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
506690  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   

        v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  v44  v45  v46  \
506686  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0   
506687  1.0  0.0  0.0  2.0  2.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
506688  0.0  1.0

In [51]:
# Checks out the shape of df_test
df_test.shape

(506691, 442)

In [52]:
# Calls info method off df_test
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506691 entries, 0 to 506690
Columns: 442 entries, transactionid to id_38
dtypes: float64(385), int64(3), object(54)
memory usage: 1.7+ GB


#### Revisiting datatypes of df_train and df_test

In [53]:
# Calls info method off df_train
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 443 entries, transactionid to id_38
dtypes: float64(385), int64(4), object(54)
memory usage: 1.9+ GB


In [54]:
# Filters df_train by columns with float64 dtype
df_train.select_dtypes(include=['float64']).head()

transactionamt  card2  card3  card5  addr1  addr2  dist1  dist2   c1   c2  \
0            68.5    NaN  150.0  142.0  315.0   87.0   19.0    NaN  1.0  1.0   
1            29.0  404.0  150.0  102.0  325.0   87.0    NaN    NaN  1.0  1.0   
2            59.0  490.0  150.0  166.0  330.0   87.0  287.0    NaN  1.0  1.0   
3            50.0  567.0  150.0  117.0  476.0   87.0    NaN    NaN  2.0  5.0   
4            50.0  514.0  150.0  102.0  420.0   87.0    NaN    NaN  1.0  1.0   

    c3   c4   c5   c6   c7   c8   c9  c10  c11  c12   c13  c14     d1     d2  \
0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  2.0  0.0   1.0  1.0   14.0    NaN   
1  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   1.0  1.0    0.0    NaN   
2  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0   1.0  1.0    0.0    NaN   
3  0.0  0.0  0.0  4.0  0.0  0.0  1.0  0.0  1.0  0.0  25.0  1.0  112.0  112.0   
4  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0   1.0  1.0    0.0    NaN   

     d3    d4   d5  d6  d7  d8  d9   d10    d11  d12  d13  d14    d15   v1  \
0  13.0   NaN  NaN NaN NaN NaN NaN  13.0   13.0  NaN  NaN  NaN    0.0  1.0   
1   NaN   0.0  NaN NaN NaN NaN NaN   0.0    NaN  NaN  NaN  NaN    0.0  NaN   
2   NaN   0.0  NaN NaN NaN NaN NaN   0.0  315.0  NaN  NaN  NaN  315.0  1.0   
3   0.0  94.0  0.0 NaN NaN NaN NaN  84.0    NaN  NaN  NaN  NaN  111.0  NaN   
4   NaN   NaN  NaN NaN NaN NaN NaN   NaN    NaN  NaN  NaN  NaN    NaN  NaN   

    v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  \
0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v30  v31  v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  \
0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v44  v45  v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  v57  v58  \
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0  0.0  0.0   
1  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
2  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v59  v60  v61  v62  v63  v64  v65  v66  v67  v68  v69  v70  v71  v72  v73  \
0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v74  v75  v76  v77  v78  v79  v80  v81  v82  v83  v84  v85  v86  v87  v88  \
0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0   
1  0.0 

In [55]:
# Filters df_train by columns with int64 dtype 
df_train.select_dtypes(include=['int64']).head()

transactionid  isfraud  transactiondt  card1
0        2987000        0          86400  13926
1        2987001        0          86401   2755
2        2987002        0          86469   4663
3        2987003        0          86499  18132
4        2987004        0          86506   4497

In [56]:
# Filters df_train by columns with object dtype
df_train.select_dtypes(include=['object']).head()

productcd       card4   card6 p_emaildomain r_emaildomain   m1   m2   m3  \
0         W    discover  credit           NaN           NaN    T    T    T   
1         W  mastercard  credit     gmail.com           NaN  NaN  NaN  NaN   
2         W        visa   debit   outlook.com           NaN    T    T    T   
3         W  mastercard   debit     yahoo.com           NaN  NaN  NaN  NaN   
4         H  mastercard  credit     gmail.com           NaN  NaN  NaN  NaN   

    m4   m5   m6   m7   m8   m9                     DeviceInfo DeviceType  \
0   M2    F    T  NaN  NaN  NaN                            NaN        NaN   
1   M0    T    T  NaN  NaN  NaN                            NaN        NaN   
2   M0    F    F    F    F    F                            NaN        NaN   
3   M0    T    F  NaN  NaN  NaN                            NaN        NaN   
4  NaN  NaN  NaN  NaN  NaN  NaN  SAMSUNG SM-G892A Build/NRD90M     mobile   

  id_01    id_02 id_03 id_04 id_05 id_06 id_07 id_08 id_09 id_10  id_11  \
0   NaN      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
1   NaN      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
2   NaN      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
3   NaN      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN   
4   0.0  70787.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  100.0   

      id_12 id_13   id_14 id_15     id_16  id_17 id_18  id_19  id_20 id_21  \
0       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
1       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
2       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
3       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
4  NotFound   NaN  -480.0   New  NotFound  166.0   NaN  542.0  144.0   NaN   

  id_22 id_23 id_24 id_25 id_26 id_27 id_28     id_29        id_30  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
4   NaN   NaN   NaN   NaN   NaN   NaN   New  NotFound  Android 7.0   

                 id_31 id_32      id_33           id_34 id_35 id_36 id_37  \
0                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
1                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
2                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
3                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
4  samsung browser 6.2  32.0  2220x1080  match_status:2     T     F     T   

  id_38  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4     T

In [57]:
# Converts the data in df_train columns defined in numeric_cols list from object dtype to numeric dtype
# I make this conversion, because these columns are not listed as being object datatypes on the data page of the Kaggle competition
numeric_cols = ['id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06', 'id_07', 'id_08', 'id_09', 'id_10', 'id_11']

for col in numeric_cols:
    df_train[col] = pd.to_numeric(df_train[col])

In [58]:
# Filters df_train by columns with object dtype
df_train.select_dtypes(include=['object']).head()

productcd       card4   card6 p_emaildomain r_emaildomain   m1   m2   m3  \
0         W    discover  credit           NaN           NaN    T    T    T   
1         W  mastercard  credit     gmail.com           NaN  NaN  NaN  NaN   
2         W        visa   debit   outlook.com           NaN    T    T    T   
3         W  mastercard   debit     yahoo.com           NaN  NaN  NaN  NaN   
4         H  mastercard  credit     gmail.com           NaN  NaN  NaN  NaN   

    m4   m5   m6   m7   m8   m9                     DeviceInfo DeviceType  \
0   M2    F    T  NaN  NaN  NaN                            NaN        NaN   
1   M0    T    T  NaN  NaN  NaN                            NaN        NaN   
2   M0    F    F    F    F    F                            NaN        NaN   
3   M0    T    F  NaN  NaN  NaN                            NaN        NaN   
4  NaN  NaN  NaN  NaN  NaN  NaN  SAMSUNG SM-G892A Build/NRD90M     mobile   

      id_12 id_13   id_14 id_15     id_16  id_17 id_18  id_19  id_20 id_21  \
0       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
1       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
2       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
3       NaN   NaN     NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   
4  NotFound   NaN  -480.0   New  NotFound  166.0   NaN  542.0  144.0   NaN   

  id_22 id_23 id_24 id_25 id_26 id_27 id_28     id_29        id_30  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
4   NaN   NaN   NaN   NaN   NaN   NaN   New  NotFound  Android 7.0   

                 id_31 id_32      id_33           id_34 id_35 id_36 id_37  \
0                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
1                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
2                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
3                  NaN   NaN        NaN             NaN   NaN   NaN   NaN   
4  samsung browser 6.2  32.0  2220x1080  match_status:2     T     F     T   

  id_38  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4     T

In [59]:
# Calls info method off df_train
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 443 entries, transactionid to id_38
dtypes: float64(396), int64(4), object(43)
memory usage: 1.9+ GB


- df_train has 590540 rows of data with 443 variables
- 396 variables in df_train are float64
- 4 variables are int64
- 43 variables are object

In [60]:
# Calls info method off df_test
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506691 entries, 0 to 506690
Columns: 442 entries, transactionid to id_38
dtypes: float64(385), int64(3), object(54)
memory usage: 1.7+ GB


In [61]:
# Filters df_test by columns with float64 dtype
df_test.select_dtypes(include=['float64']).head()

transactionamt  card2  card3  card5  addr1  addr2   dist1  dist2   c1   c2  \
0           31.95  111.0  150.0  226.0  170.0   87.0     1.0    NaN  6.0  6.0   
1           49.00  111.0  150.0  226.0  299.0   87.0     4.0    NaN  3.0  2.0   
2          171.00  574.0  150.0  226.0  472.0   87.0  2635.0    NaN  2.0  2.0   
3          284.95  360.0  150.0  166.0  205.0   87.0    17.0    NaN  5.0  2.0   
4           67.95  452.0  150.0  117.0  264.0   87.0     6.0    NaN  6.0  6.0   

    c3   c4   c5   c6   c7   c8   c9  c10  c11  c12    c13  c14     d1     d2  \
0  0.0  0.0  3.0  4.0  0.0  0.0  6.0  0.0  5.0  1.0  115.0  6.0  419.0  419.0   
1  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  1.0  1.0   12.0  2.0  149.0  149.0   
2  0.0  0.0  0.0  5.0  0.0  0.0  4.0  0.0  2.0  0.0   22.0  2.0  137.0  137.0   
3  0.0  0.0  1.0  1.0  0.0  0.0  2.0  0.0  2.0  0.0    7.0  4.0   42.0   42.0   
4  0.0  0.0  2.0  5.0  0.0  0.0  5.0  0.0  6.0  0.0   14.0  6.0   22.0   22.0   

     d3     d4    d5  d6  d7  d8  d9    d10    d11  d12  d13  d14    d15   v1  \
0  27.0  398.0  27.0 NaN NaN NaN NaN  418.0  203.0  NaN  NaN  NaN  409.0  1.0   
1   7.0  634.0   7.0 NaN NaN NaN NaN  231.0  634.0  NaN  NaN  NaN  634.0  1.0   
2  10.0   97.0  10.0 NaN NaN NaN NaN  136.0  136.0  NaN  NaN  NaN   97.0  1.0   
3  41.0  242.0  41.0 NaN NaN NaN NaN  242.0  242.0  NaN  NaN  NaN  242.0  1.0   
4   0.0   22.0   0.0 NaN NaN NaN NaN   22.0   22.0  NaN  NaN  NaN   22.0  1.0   

    v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   

   v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  2.0  1.0  1.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0   
4  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0   

   v30  v31  v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  \
0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   
3  1.0  0.0  0.0  0.0  0.0  2.0  2.0  2.0  2.0  0.0  0.0  1.0  0.0  0.0  0.0   
4  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0   

   v44  v45  v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  v57  v58  \
0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
1  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
2  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
3  2.0  2.0  2.0  2.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   

   v59  v60  v61  v62  v63  v64  v65  v66  v67  v68  v69  v70  v71  v72  v73  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0   
4  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0   

   v74  v75  v76  v77  v78  v79  v80  v81  v82  v83  v84  v85  v86  v87  v88  \
0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0 

In [62]:
# Filters df_test by columns with int64 dtype
df_test.select_dtypes(include=['int64']).head()

transactionid  transactiondt  card1
0        3663549       18403224  10409
1        3663550       18403263   4272
2        3663551       18403310   4476
3        3663552       18403310  10989
4        3663553       18403317  18018

In [63]:
# Filters df_test by columns with object dtype
df_test.select_dtypes(include=['object']).head()

productcd       card4  card6 p_emaildomain r_emaildomain m1 m2 m3   m4   m5  \
0         W        visa  debit     gmail.com           NaN  T  T  F  NaN  NaN   
1         W        visa  debit       aol.com           NaN  T  F  F   M0  NaN   
2         W        visa  debit   hotmail.com           NaN  T  T  F   M0    F   
3         W        visa  debit     gmail.com           NaN  T  T  T  NaN  NaN   
4         W  mastercard  debit     gmail.com           NaN  T  T  T  NaN  NaN   

  m6   m7   m8   m9 DeviceInfo DeviceType id_01 id_02 id_03 id_04 id_05 id_06  \
0  F    T    T    T        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1  F  NaN  NaN  NaN        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2  F    F    F    F        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3  T  NaN  NaN  NaN        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4  F    F    T    T        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   

  id_07 id_08 id_09 id_10 id_11 id_12 id_13 id_14 id_15 id_16 id_17 id_18  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

  id_19 id_20 id_21 id_22 id_23 id_24 id_25 id_26 id_27 id_28 id_29 id_30  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

  id_31 id_32 id_33 id_34 id_35 id_36 id_37 id_38  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [64]:
# Converts the data in df_test columns defined in numeric_cols list from object dtype to numeric dtype
numeric_cols = ['id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06', 'id_07', 'id_08', 'id_09', 'id_10', 'id_11']

for col in numeric_cols:
    df_test[col] = pd.to_numeric(df_test[col])

In [65]:
# Filters df_test by columns with object dtype
df_test.select_dtypes(include=['object']).head()

productcd       card4  card6 p_emaildomain r_emaildomain m1 m2 m3   m4   m5  \
0         W        visa  debit     gmail.com           NaN  T  T  F  NaN  NaN   
1         W        visa  debit       aol.com           NaN  T  F  F   M0  NaN   
2         W        visa  debit   hotmail.com           NaN  T  T  F   M0    F   
3         W        visa  debit     gmail.com           NaN  T  T  T  NaN  NaN   
4         W  mastercard  debit     gmail.com           NaN  T  T  T  NaN  NaN   

  m6   m7   m8   m9 DeviceInfo DeviceType id_12 id_13 id_14 id_15 id_16 id_17  \
0  F    T    T    T        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1  F  NaN  NaN  NaN        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2  F    F    F    F        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3  T  NaN  NaN  NaN        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4  F    F    T    T        NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN   

  id_18 id_19 id_20 id_21 id_22 id_23 id_24 id_25 id_26 id_27 id_28 id_29  \
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

  id_30 id_31 id_32 id_33 id_34 id_35 id_36 id_37 id_38  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [66]:
# Calls info method off df_test
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506691 entries, 0 to 506690
Columns: 442 entries, transactionid to id_38
dtypes: float64(396), int64(3), object(43)
memory usage: 1.7+ GB


- df_test has 506691 rows of data with 442 variables
- 396 variables in df_train are float64
- 3 variables are int64
- 43 variables are object

### Indexing
Which variable or variables should you index on? Depending on your dataset, this may or may not have a simple answer. Regardless, choose one or more index values for your data set.

In [67]:
# Looks at the first five rows of df_train
df_train.head()

transactionid  isfraud  transactiondt  transactionamt productcd  card1  \
0        2987000        0          86400            68.5         W  13926   
1        2987001        0          86401            29.0         W   2755   
2        2987002        0          86469            59.0         W   4663   
3        2987003        0          86499            50.0         W  18132   
4        2987004        0          86506            50.0         H   4497   

   card2  card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
0    NaN  150.0    discover  142.0  credit  315.0   87.0   19.0    NaN   
1  404.0  150.0  mastercard  102.0  credit  325.0   87.0    NaN    NaN   
2  490.0  150.0        visa  166.0   debit  330.0   87.0  287.0    NaN   
3  567.0  150.0  mastercard  117.0   debit  476.0   87.0    NaN    NaN   
4  514.0  150.0  mastercard  102.0  credit  420.0   87.0    NaN    NaN   

  p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8   c9  \
0           NaN           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
1     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
2   outlook.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0   
3     yahoo.com           NaN  2.0  5.0  0.0  0.0  0.0  4.0  0.0  0.0  1.0   
4     gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   

   c10  c11  c12   c13  c14     d1     d2    d3    d4   d5  d6  d7  d8  d9  \
0  0.0  2.0  0.0   1.0  1.0   14.0    NaN  13.0   NaN  NaN NaN NaN NaN NaN   
1  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
2  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
3  0.0  1.0  0.0  25.0  1.0  112.0  112.0   0.0  94.0  0.0 NaN NaN NaN NaN   
4  1.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   NaN  NaN NaN NaN NaN NaN   

    d10    d11  d12  d13  d14    d15   m1   m2   m3   m4   m5   m6   m7   m8  \
0  13.0   13.0  NaN  NaN  NaN    0.0    T    T    T   M2    F    T  NaN  NaN   
1   0.0    NaN  NaN  NaN  NaN    0.0  NaN  NaN  NaN   M0    T    T  NaN  NaN   
2   0.0  315.0  NaN  NaN  NaN  315.0    T    T    T   M0    F    F    F    F   
3  84.0    NaN  NaN  NaN  NaN  111.0  NaN  NaN  NaN   M0    T    F  NaN  NaN   
4   NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    m9   v1   v2   v3   v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  \
0  NaN  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0   
2    F  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0   
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v13  v14  v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  \
0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
3  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

   v42  v43  v44  v45  v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  \
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0   
1  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

In [68]:
# Looks at the count of null values in the transactionid column of df_train
df_train_null_counts = null_counts(df_train)
df_train_null_counts_reset_index = df_train_null_counts.sort_values(by='null_fraction').head().reset_index()
df_train_null_counts_reset_index[df_train_null_counts_reset_index['index']=='transactionid']

index  null_count  null_fraction
3  transactionid           0            0.0

In [69]:
# Checks for duplicates in the transactionid column of df_train
df_train['transactionid'].duplicated().any()

np.False_

In [70]:
# Sets the transactionid column as the index of df_train and looks at the first 5 rows
df_train = df_train.set_index('transactionid')
df_train.head()

isfraud  transactiondt  transactionamt productcd  card1  card2  \
transactionid                                                                   
2987000              0          86400            68.5         W  13926    NaN   
2987001              0          86401            29.0         W   2755  404.0   
2987002              0          86469            59.0         W   4663  490.0   
2987003              0          86499            50.0         W  18132  567.0   
2987004              0          86506            50.0         H   4497  514.0   

               card3       card4  card5   card6  addr1  addr2  dist1  dist2  \
transactionid                                                                 
2987000        150.0    discover  142.0  credit  315.0   87.0   19.0    NaN   
2987001        150.0  mastercard  102.0  credit  325.0   87.0    NaN    NaN   
2987002        150.0        visa  166.0   debit  330.0   87.0  287.0    NaN   
2987003        150.0  mastercard  117.0   debit  476.0   87.0    NaN    NaN   
2987004        150.0  mastercard  102.0  credit  420.0   87.0    NaN    NaN   

              p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7  \
transactionid                                                                  
2987000                 NaN           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0   
2987001           gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0   
2987002         outlook.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0   
2987003           yahoo.com           NaN  2.0  5.0  0.0  0.0  0.0  4.0  0.0   
2987004           gmail.com           NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0   

                c8   c9  c10  c11  c12   c13  c14     d1     d2    d3    d4  \
transactionid                                                                 
2987000        0.0  1.0  0.0  2.0  0.0   1.0  1.0   14.0    NaN  13.0   NaN   
2987001        0.0  0.0  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0   
2987002        0.0  1.0  0.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   0.0   
2987003        0.0  1.0  0.0  1.0  0.0  25.0  1.0  112.0  112.0   0.0  94.0   
2987004        1.0  0.0  1.0  1.0  0.0   1.0  1.0    0.0    NaN   NaN   NaN   

                d5  d6  d7  d8  d9   d10    d11  d12  d13  d14    d15   m1  \
transactionid                                                                
2987000        NaN NaN NaN NaN NaN  13.0   13.0  NaN  NaN  NaN    0.0    T   
2987001        NaN NaN NaN NaN NaN   0.0    NaN  NaN  NaN  NaN    0.0  NaN   
2987002        NaN NaN NaN NaN NaN   0.0  315.0  NaN  NaN  NaN  315.0    T   
2987003        0.0 NaN NaN NaN NaN  84.0    NaN  NaN  NaN  NaN  111.0  NaN   
2987004        NaN NaN NaN NaN NaN   NaN    NaN  NaN  NaN  NaN    NaN  NaN   

                m2   m3   m4   m5   m6   m7   m8   m9   v1   v2   v3   v4  \
transactionid                                                               
2987000          T    T   M2    F    T  NaN  NaN  NaN  1.0  1.0  1.0  1.0   
2987001        NaN  NaN   M0    T    T  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2987002          T    T   M0    F    F    F    F    F  1.0  1.0  1.0  1.0   
2987003        NaN  NaN   M0    T    F  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2987004        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

                v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  \
transactionid                                                               
2987000        1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
2987001        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0   
2987002        1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
2987003        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0   
2987004        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

               v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  \
transactionid                                                             

In [71]:
# Calls the info method off df_train
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 590540 entries, 2987000 to 3577539
Columns: 442 entries, isfraud to id_38
dtypes: float64(396), int64(3), object(43)
memory usage: 1.9+ GB


In [72]:
# Looks at the first five rows of df_test
df_test.head()

transactionid  transactiondt  transactionamt productcd  card1  card2  \
0        3663549       18403224           31.95         W  10409  111.0   
1        3663550       18403263           49.00         W   4272  111.0   
2        3663551       18403310          171.00         W   4476  574.0   
3        3663552       18403310          284.95         W  10989  360.0   
4        3663553       18403317           67.95         W  18018  452.0   

   card3       card4  card5  card6  addr1  addr2   dist1  dist2 p_emaildomain  \
0  150.0        visa  226.0  debit  170.0   87.0     1.0    NaN     gmail.com   
1  150.0        visa  226.0  debit  299.0   87.0     4.0    NaN       aol.com   
2  150.0        visa  226.0  debit  472.0   87.0  2635.0    NaN   hotmail.com   
3  150.0        visa  166.0  debit  205.0   87.0    17.0    NaN     gmail.com   
4  150.0  mastercard  117.0  debit  264.0   87.0     6.0    NaN     gmail.com   

  r_emaildomain   c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  c12  \
0           NaN  6.0  6.0  0.0  0.0  3.0  4.0  0.0  0.0  6.0  0.0  5.0  1.0   
1           NaN  3.0  2.0  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  1.0  1.0   
2           NaN  2.0  2.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0  0.0  2.0  0.0   
3           NaN  5.0  2.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  0.0  2.0  0.0   
4           NaN  6.0  6.0  0.0  0.0  2.0  5.0  0.0  0.0  5.0  0.0  6.0  0.0   

     c13  c14     d1     d2    d3     d4    d5  d6  d7  d8  d9    d10    d11  \
0  115.0  6.0  419.0  419.0  27.0  398.0  27.0 NaN NaN NaN NaN  418.0  203.0   
1   12.0  2.0  149.0  149.0   7.0  634.0   7.0 NaN NaN NaN NaN  231.0  634.0   
2   22.0  2.0  137.0  137.0  10.0   97.0  10.0 NaN NaN NaN NaN  136.0  136.0   
3    7.0  4.0   42.0   42.0  41.0  242.0  41.0 NaN NaN NaN NaN  242.0  242.0   
4   14.0  6.0   22.0   22.0   0.0   22.0   0.0 NaN NaN NaN NaN   22.0   22.0   

   d12  d13  d14    d15 m1 m2 m3   m4   m5 m6   m7   m8   m9   v1   v2   v3  \
0  NaN  NaN  NaN  409.0  T  T  F  NaN  NaN  F    T    T    T  1.0  1.0  1.0   
1  NaN  NaN  NaN  634.0  T  F  F   M0  NaN  F  NaN  NaN  NaN  1.0  1.0  1.0   
2  NaN  NaN  NaN   97.0  T  T  F   M0    F  F    F    F    F  1.0  1.0  1.0   
3  NaN  NaN  NaN  242.0  T  T  T  NaN  NaN  T  NaN  NaN  NaN  1.0  1.0  1.0   
4  NaN  NaN  NaN   22.0  T  T  T  NaN  NaN  F    F    T    T  1.0  1.0  1.0   

    v4   v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  v16  \
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   

   v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  v28  v29  v30  v31  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
2  0.0  0.0  1.0  1.0  0.0  0.0  2.0  2.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0   
3  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0   
4  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0   

   v32  v33  v34  v35  v36  v37  v38  v39  v40  v41  v42  v42  v43  v44  v45  \
0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
1  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
2  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   
3  0.0  0.0  0.0  2.0  2.0  2.0  2.0  0.0  0.0  1.0  0.0  0.0  0.0  2.0  2.0   
4  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0   

   v46  v47  v48  v49  v50  v51  v52  v53  v54  v55  v56  v57  v58  v59  v60  \
0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0   
1  1.0  1.0  0.0  0.0  0.0  0.0

In [73]:
# Looks at the count of null values in the transactionid column of df_test
df_test_null_counts = null_counts(df_test)
df_test_null_counts_reset_index = df_test_null_counts.sort_values(by='null_fraction').head().reset_index()
df_test_null_counts_reset_index[df_test_null_counts_reset_index['index']=='transactionid']

index  null_count  null_fraction
3  transactionid           0            0.0

In [74]:
# Checks for duplicates in the transactionid column of df_test
df_test['transactionid'].duplicated().any()

np.False_

In [75]:
# Sets the transactionid column as the index of df_test and looks at the first 5 rows
df_test = df_test.set_index('transactionid')
df_test.head()

transactiondt  transactionamt productcd  card1  card2  card3  \
transactionid                                                                 
3663549             18403224           31.95         W  10409  111.0  150.0   
3663550             18403263           49.00         W   4272  111.0  150.0   
3663551             18403310          171.00         W   4476  574.0  150.0   
3663552             18403310          284.95         W  10989  360.0  150.0   
3663553             18403317           67.95         W  18018  452.0  150.0   

                    card4  card5  card6  addr1  addr2   dist1  dist2  \
transactionid                                                          
3663549              visa  226.0  debit  170.0   87.0     1.0    NaN   
3663550              visa  226.0  debit  299.0   87.0     4.0    NaN   
3663551              visa  226.0  debit  472.0   87.0  2635.0    NaN   
3663552              visa  166.0  debit  205.0   87.0    17.0    NaN   
3663553        mastercard  117.0  debit  264.0   87.0     6.0    NaN   

              p_emaildomain r_emaildomain   c1   c2   c3   c4   c5   c6   c7  \
transactionid                                                                  
3663549           gmail.com           NaN  6.0  6.0  0.0  0.0  3.0  4.0  0.0   
3663550             aol.com           NaN  3.0  2.0  0.0  0.0  0.0  1.0  0.0   
3663551         hotmail.com           NaN  2.0  2.0  0.0  0.0  0.0  5.0  0.0   
3663552           gmail.com           NaN  5.0  2.0  0.0  0.0  1.0  1.0  0.0   
3663553           gmail.com           NaN  6.0  6.0  0.0  0.0  2.0  5.0  0.0   

                c8   c9  c10  c11  c12    c13  c14     d1     d2    d3     d4  \
transactionid                                                                   
3663549        0.0  6.0  0.0  5.0  1.0  115.0  6.0  419.0  419.0  27.0  398.0   
3663550        0.0  2.0  0.0  1.0  1.0   12.0  2.0  149.0  149.0   7.0  634.0   
3663551        0.0  4.0  0.0  2.0  0.0   22.0  2.0  137.0  137.0  10.0   97.0   
3663552        0.0  2.0  0.0  2.0  0.0    7.0  4.0   42.0   42.0  41.0  242.0   
3663553        0.0  5.0  0.0  6.0  0.0   14.0  6.0   22.0   22.0   0.0   22.0   

                 d5  d6  d7  d8  d9    d10    d11  d12  d13  d14    d15 m1 m2  \
transactionid                                                                   
3663549        27.0 NaN NaN NaN NaN  418.0  203.0  NaN  NaN  NaN  409.0  T  T   
3663550         7.0 NaN NaN NaN NaN  231.0  634.0  NaN  NaN  NaN  634.0  T  F   
3663551        10.0 NaN NaN NaN NaN  136.0  136.0  NaN  NaN  NaN   97.0  T  T   
3663552        41.0 NaN NaN NaN NaN  242.0  242.0  NaN  NaN  NaN  242.0  T  T   
3663553         0.0 NaN NaN NaN NaN   22.0   22.0  NaN  NaN  NaN   22.0  T  T   

              m3   m4   m5 m6   m7   m8   m9   v1   v2   v3   v4   v5   v5  \
transactionid                                                                
3663549        F  NaN  NaN  F    T    T    T  1.0  1.0  1.0  1.0  1.0  1.0   
3663550        F   M0  NaN  F  NaN  NaN  NaN  1.0  1.0  1.0  1.0  1.0  1.0   
3663551        F   M0    F  F    F    F    F  1.0  1.0  1.0  1.0  1.0  1.0   
3663552        T  NaN  NaN  T  NaN  NaN  NaN  1.0  1.0  1.0  1.0  1.0  1.0   
3663553        T  NaN  NaN  F    F    T    T  1.0  1.0  1.0  1.0  1.0  1.0   

                v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  v16  \
transactionid                                                               
3663549        1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
3663550        1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
3663551        1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0   
3663552        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   
3663553        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   

               v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  v28  \
transactionid                                                               
3663549        0.0

In [76]:
# Calls the info method off df_test
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 506691 entries, 3663549 to 4170239
Columns: 441 entries, transactiondt to id_38
dtypes: float64(396), int64(2), object(43)
memory usage: 1.7+ GB


### Variable Names
Depending on your data set, variables may have names with strange symbols, which can making loading, saving, and subsetting data difficult. If applicable, you should deal with this now.

- I standardized the column names of every df after loading in the csv file

### Duplicates
Deal with any duplicate rows/columns (or, contrarily, any empty rows/columns), if applicable.

In [77]:
# Looks at the shape of df_train
df_train.shape

(590540, 442)

In [78]:
# Drops duplicates from df_train
df_train = df_train.drop_duplicates()

In [79]:
# Looks at the shape of df_train after dropping duplicates
df_train.shape

(590537, 442)

In [80]:
# Looks at the shape of df_test
df_test.shape

(506691, 441)

In [81]:
# Drops duplicates from df_test
df_test = df_test.drop_duplicates()

In [82]:
# Looks at the shape of df_test after dropping duplicates
df_test.shape

(506691, 441)

In [83]:
# Creates a dictionary from df_train where the keys are columns names and the values are lists of the index positions that have the same column name
df_train_duplicate_cols = {}
for idx, col in enumerate(df_train.columns):
    if col in df_train_duplicate_cols:
        df_train_duplicate_cols[col].append(idx)
    else:
        df_train_duplicate_cols[col] = [idx]

In [84]:
# Uses the dictionary made from df_train to check if columns that share the same name are duplicates or not 
for cols, indices in df_train_duplicate_cols.items():
    if len(indices) > 1:
        print(f"Column {cols} appears at index positions: {indices}")
        true_false = df_train.iloc[:, indices[0]] == df_train.iloc[:, indices[1]]
        true_false_all = true_false.all()
        if true_false_all == np.False_:
            print(f"The columns at index {indices[0]} and {indices[1]} are not duplicates.")
            print(f"At least one row of data in the column at index {indices[0]} is different than the column at index {indices[1]}.")
        else:
            print(f"The column at index {indices[0]} is different than the column in {indices[1]}")
            print(f"All data in the column at index {indices[0]} is the same as the data the column in {indices[1]}")
        print("---")

Column v5 appears at index positions: [58, 59]
The columns at index 58 and 59 are not duplicates.
At least one row of data in the column at index 58 is different than the column at index 59.
---
Column v12 appears at index positions: [66, 67]
The columns at index 66 and 67 are not duplicates.
At least one row of data in the column at index 66 is different than the column at index 67.
---
Column v42 appears at index positions: [97, 98]
The columns at index 97 and 98 are not duplicates.
At least one row of data in the column at index 97 is different than the column at index 98.
---
Column v139 appears at index positions: [195, 196]
The columns at index 195 and 196 are not duplicates.
At least one row of data in the column at index 195 is different than the column at index 196.
---
Column v157 appears at index positions: [214, 215]
The columns at index 214 and 215 are not duplicates.
At least one row of data in the column at index 214 is different than the column at index 215.
---
Column 

In [85]:
# Creates a dictionary from df_test where the keys are columns names and the values are lists of the index positions that have the same column name
df_test_duplicate_cols = {}
for idx_test, col_test in enumerate(df_test.columns):
    if col_test in df_test_duplicate_cols:
        df_test_duplicate_cols[col_test].append(idx_test)
    else:
        df_test_duplicate_cols[col_test] = [idx_test]

In [86]:
# Uses the dictionary made from df_test to check if columns that share the same name are duplicates or not
for cols_test, indices_test in df_test_duplicate_cols.items():
    if len(indices_test) > 1:
        print(f"Column {cols_test} appears at index positions: {indices_test}")
        test_true_false = df_test.iloc[:, indices_test[0]] == df_test.iloc[:, indices_test[1]]
        test_true_false_all = test_true_false.all()
        if test_true_false_all == np.False_:
            print(f"The columns at index {indices_test[0]} and {indices_test[1]} are not duplicates.")
            print(f"At least one row of data in the column at index {indices_test[0]} is different than the column at index {indices_test[1]}.")
        else:
            print(f"The column at index {indices_test[0]} is different than the column in {indices_test[1]}")
            print(f"All data in the column at index {indices_test[0]} is the same as the data the column in {indices_test[1]}")
        print("---")

Column v5 appears at index positions: [57, 58]
The columns at index 57 and 58 are not duplicates.
At least one row of data in the column at index 57 is different than the column at index 58.
---
Column v12 appears at index positions: [65, 66]
The columns at index 65 and 66 are not duplicates.
At least one row of data in the column at index 65 is different than the column at index 66.
---
Column v42 appears at index positions: [96, 97]
The columns at index 96 and 97 are not duplicates.
At least one row of data in the column at index 96 is different than the column at index 97.
---
Column v139 appears at index positions: [194, 195]
The columns at index 194 and 195 are not duplicates.
At least one row of data in the column at index 194 is different than the column at index 195.
---
Column v157 appears at index positions: [213, 214]
The columns at index 213 and 214 are not duplicates.
At least one row of data in the column at index 213 is different than the column at index 214.
---
Column 

### Categorical Encoding
Are there any categorical variables in your data? If so, how would you deal with this so that it can be handled by a machine learning algorithm? You're free to implement the solution now or during your model training process, whichever suits you better.

In [87]:
# Filters df_train by columns with the object datatype
df_train.select_dtypes(include=['object']).head()

productcd       card4   card6 p_emaildomain r_emaildomain   m1  \
transactionid                                                                  
2987000               W    discover  credit           NaN           NaN    T   
2987001               W  mastercard  credit     gmail.com           NaN  NaN   
2987002               W        visa   debit   outlook.com           NaN    T   
2987003               W  mastercard   debit     yahoo.com           NaN  NaN   
2987004               H  mastercard  credit     gmail.com           NaN  NaN   

                m2   m3   m4   m5   m6   m7   m8   m9  \
transactionid                                           
2987000          T    T   M2    F    T  NaN  NaN  NaN   
2987001        NaN  NaN   M0    T    T  NaN  NaN  NaN   
2987002          T    T   M0    F    F    F    F    F   
2987003        NaN  NaN   M0    T    F  NaN  NaN  NaN   
2987004        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

                                  DeviceInfo DeviceType     id_12 id_13  \
transactionid                                                             
2987000                                  NaN        NaN       NaN   NaN   
2987001                                  NaN        NaN       NaN   NaN   
2987002                                  NaN        NaN       NaN   NaN   
2987003                                  NaN        NaN       NaN   NaN   
2987004        SAMSUNG SM-G892A Build/NRD90M     mobile  NotFound   NaN   

                id_14 id_15     id_16  id_17 id_18  id_19  id_20 id_21 id_22  \
transactionid                                                                  
2987000           NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   NaN   
2987001           NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   NaN   
2987002           NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   NaN   
2987003           NaN   NaN       NaN    NaN   NaN    NaN    NaN   NaN   NaN   
2987004        -480.0   New  NotFound  166.0   NaN  542.0  144.0   NaN   NaN   

              id_23 id_24 id_25 id_26 id_27 id_28     id_29        id_30  \
transactionid                                                              
2987000         NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
2987001         NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
2987002         NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
2987003         NaN   NaN   NaN   NaN   NaN   NaN       NaN          NaN   
2987004         NaN   NaN   NaN   NaN   NaN   New  NotFound  Android 7.0   

                             id_31 id_32      id_33           id_34 id_35  \
transactionid                                                               
2987000                        NaN   NaN        NaN             NaN   NaN   
2987001                        NaN   NaN        NaN             NaN   NaN   
2987002                        NaN   NaN        NaN             NaN   NaN   
2987003                        NaN   NaN        NaN             NaN   NaN   
2987004        samsung browser 6.2  32.0  2220x1080  match_status:2     T   

              id_36 id_37 id_38  
transactionid                    
2987000         NaN   NaN   NaN  
2987001         NaN   NaN   NaN  
2987002         NaN   NaN   NaN  
2987003         NaN   NaN   NaN  
2987004           F     T     T

In [88]:
# Creates a dictionary where the keys are column names in df_train with object data and the values are the number of unique values in eacb column
df_train_object_nunique_dict = {col: df_train[col].nunique() for col in df_train.select_dtypes(include=['object']).columns}
df_train_object_nunique_dict

{'productcd': 5,
 'card4': 4,
 'card6': 4,
 'p_emaildomain': 59,
 'r_emaildomain': 60,
 'm1': 2,
 'm2': 2,
 'm3': 2,
 'm4': 3,
 'm5': 2,
 'm6': 2,
 'm7': 2,
 'm8': 2,
 'm9': 2,
 'DeviceInfo': 1786,
 'DeviceType': 2,
 'id_12': 2,
 'id_13': 54,
 'id_14': 25,
 'id_15': 3,
 'id_16': 2,
 'id_17': 104,
 'id_18': 18,
 'id_19': 522,
 'id_20': 394,
 'id_21': 490,
 'id_22': 25,
 'id_23': 3,
 'id_24': 12,
 'id_25': 341,
 'id_26': 95,
 'id_27': 2,
 'id_28': 2,
 'id_29': 2,
 'id_30': 75,
 'id_31': 130,
 'id_32': 4,
 'id_33': 260,
 'id_34': 4,
 'id_35': 2,
 'id_36': 2,
 'id_37': 2,
 'id_38': 2}

In [89]:
# Creates a dictionary where the keys are column names in df_train with object data and the values are dictionaries of the value counts of each column
df_train_object_value_counts_dict = {col: df_train[col].value_counts().to_dict() for col in df_train.select_dtypes(include=['object']).columns}

In [90]:
# Filters df_test by columns with the object datatype
df_test.select_dtypes(include=['object']).head()

productcd       card4  card6 p_emaildomain r_emaildomain m1 m2  \
transactionid                                                                  
3663549               W        visa  debit     gmail.com           NaN  T  T   
3663550               W        visa  debit       aol.com           NaN  T  F   
3663551               W        visa  debit   hotmail.com           NaN  T  T   
3663552               W        visa  debit     gmail.com           NaN  T  T   
3663553               W  mastercard  debit     gmail.com           NaN  T  T   

              m3   m4   m5 m6   m7   m8   m9 DeviceInfo DeviceType id_12  \
transactionid                                                              
3663549        F  NaN  NaN  F    T    T    T        NaN        NaN   NaN   
3663550        F   M0  NaN  F  NaN  NaN  NaN        NaN        NaN   NaN   
3663551        F   M0    F  F    F    F    F        NaN        NaN   NaN   
3663552        T  NaN  NaN  T  NaN  NaN  NaN        NaN        NaN   NaN   
3663553        T  NaN  NaN  F    F    T    T        NaN        NaN   NaN   

              id_13 id_14 id_15 id_16 id_17 id_18 id_19 id_20 id_21 id_22  \
transactionid                                                               
3663549         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663550         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663551         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663552         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663553         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

              id_23 id_24 id_25 id_26 id_27 id_28 id_29 id_30 id_31 id_32  \
transactionid                                                               
3663549         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663550         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663551         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663552         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3663553         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

              id_33 id_34 id_35 id_36 id_37 id_38  
transactionid                                      
3663549         NaN   NaN   NaN   NaN   NaN   NaN  
3663550         NaN   NaN   NaN   NaN   NaN   NaN  
3663551         NaN   NaN   NaN   NaN   NaN   NaN  
3663552         NaN   NaN   NaN   NaN   NaN   NaN  
3663553         NaN   NaN   NaN   NaN   NaN   NaN

In [91]:
# Creates a dictionary where the keys are column names in df_test with object data and the values are the number of unique values in eacb column
df_test_object_nunique_dict = {col: df_test[col].nunique() for col in df_test.select_dtypes(include=['object']).columns}
df_test_object_nunique_dict

{'productcd': 5,
 'card4': 4,
 'card6': 3,
 'p_emaildomain': 60,
 'r_emaildomain': 60,
 'm1': 2,
 'm2': 2,
 'm3': 2,
 'm4': 3,
 'm5': 2,
 'm6': 2,
 'm7': 2,
 'm8': 2,
 'm9': 2,
 'DeviceInfo': 2226,
 'DeviceType': 2,
 'id_12': 2,
 'id_13': 27,
 'id_14': 27,
 'id_15': 3,
 'id_16': 2,
 'id_17': 103,
 'id_18': 17,
 'id_19': 502,
 'id_20': 436,
 'id_21': 443,
 'id_22': 26,
 'id_23': 3,
 'id_24': 15,
 'id_25': 309,
 'id_26': 94,
 'id_27': 2,
 'id_28': 2,
 'id_29': 2,
 'id_30': 86,
 'id_31': 135,
 'id_32': 5,
 'id_33': 390,
 'id_34': 2,
 'id_35': 2,
 'id_36': 2,
 'id_37': 2,
 'id_38': 2}

In [92]:
# Creates a dictionary where the keys are column names in df_test with object data and the values are dictionaries of the value counts of each column
df_test_object_value_counts_dict = {col: df_test[col].value_counts().to_dict() for col in df_test.select_dtypes(include=['object']).columns}

- I plan to encode most, if not all, the categorical data

- For an XGBoost model, I would encode the data now

- For a model that benefits from scaling, such as a neural network, I would wait until after the missing data is handled to do this
- If I wait until after the missing data is handled, I can scale the numerical columns and encode the categorical columns at the same time using a column transformer
- This will be less arduous, because the categorical columns will still have the object datatype.
- If I encoded the categorical columns before scaling the numerical columns, all the columns would have the float64 or int64 datatype and I would have to define the columns for scaling by hand
- By doing both transformation at the same type I can define the columns for encoding and the columns for scaling using the select_dtype method

### Uniformity
Are all variables measured using compatible units? Or are there monetary values in different forms of currency? Or something else entirely? If any of these issues are applicable to your data, design and implement a solution.

In [93]:
# Looks at the first five rows of data from columns with the float64 datatype in df_train
df_train.select_dtypes(include=['float64']).head()

transactionamt  card2  card3  card5  addr1  addr2  dist1  \
transactionid                                                             
2987000                  68.5    NaN  150.0  142.0  315.0   87.0   19.0   
2987001                  29.0  404.0  150.0  102.0  325.0   87.0    NaN   
2987002                  59.0  490.0  150.0  166.0  330.0   87.0  287.0   
2987003                  50.0  567.0  150.0  117.0  476.0   87.0    NaN   
2987004                  50.0  514.0  150.0  102.0  420.0   87.0    NaN   

               dist2   c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  \
transactionid                                                                 
2987000          NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  2.0   
2987001          NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0   
2987002          NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0   
2987003          NaN  2.0  5.0  0.0  0.0  0.0  4.0  0.0  0.0  1.0  0.0  1.0   
2987004          NaN  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0   

               c12   c13  c14     d1     d2    d3    d4   d5  d6  d7  d8  d9  \
transactionid                                                                  
2987000        0.0   1.0  1.0   14.0    NaN  13.0   NaN  NaN NaN NaN NaN NaN   
2987001        0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
2987002        0.0   1.0  1.0    0.0    NaN   NaN   0.0  NaN NaN NaN NaN NaN   
2987003        0.0  25.0  1.0  112.0  112.0   0.0  94.0  0.0 NaN NaN NaN NaN   
2987004        0.0   1.0  1.0    0.0    NaN   NaN   NaN  NaN NaN NaN NaN NaN   

                d10    d11  d12  d13  d14    d15   v1   v2   v3   v4   v5  \
transactionid                                                               
2987000        13.0   13.0  NaN  NaN  NaN    0.0  1.0  1.0  1.0  1.0  1.0   
2987001         0.0    NaN  NaN  NaN  NaN    0.0  NaN  NaN  NaN  NaN  NaN   
2987002         0.0  315.0  NaN  NaN  NaN  315.0  1.0  1.0  1.0  1.0  1.0   
2987003        84.0    NaN  NaN  NaN  NaN  111.0  NaN  NaN  NaN  NaN  NaN   
2987004         NaN    NaN  NaN  NaN  NaN    NaN  NaN  NaN  NaN  NaN  NaN   

                v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  v15  \
transactionid                                                               
2987000        1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987001        NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  0.0  0.0  1.0  0.0   
2987002        1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987003        NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0  1.0  1.0  0.0   
2987004        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

               v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  v27  \
transactionid                                                               
2987000        0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987001        0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987002        0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987003        0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987004        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

               v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  v38  v39  \
transactionid                                                               
2987000        0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN   
2987001        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0   
2987002        0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987003        0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  0.0   
2987004        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

               v40  v41  v42  v42  v43  v44  v45  v46  v47  v48  v49  v50  \
transactionid                                                               
2987000        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

In [94]:
# Looks at the first five rows of data from columns with the int64 datatype in df_train
df_train.select_dtypes(include=['int64']).head()

isfraud  transactiondt  card1
transactionid                               
2987000              0          86400  13926
2987001              0          86401   2755
2987002              0          86469   4663
2987003              0          86499  18132
2987004              0          86506   4497

In [95]:
# Calls the describe method on all the card columns in df_train
card_desc_dict = {}
for num in range(1,7):
    card_desc_dict[f'card{num}'] = df_train[f'card{num}'].describe()
df_card_desc = pd.DataFrame(card_desc_dict)
display_scrollable_df(df_card_desc)

In [96]:
# Calls the describe method on addr columns in df_train
addr_desc_dict = {}
for num in range(1,3):
    addr_desc_dict[f'addr{num}'] = df_train[f'addr{num}'].describe()
df_addr_desc = pd.DataFrame(addr_desc_dict)
display_scrollable_df(df_addr_desc)

In [97]:
# Calls the describe method on the dist columns in df_train
dist_desc_dict = {}
for num in range(1,3):
    dist_desc_dict[f'dist{num}'] = df_train[f'dist{num}'].describe()
df_dist_desc = pd.DataFrame(dist_desc_dict)
display_scrollable_df(df_dist_desc)

In [98]:
# Calls the describe method on all the c columns in df_train
c_desc_dict = {}
for num in range(1,15):
    c_desc_dict[f'c{num}'] = df_train[f'c{num}'].describe()
df_c_desc = pd.DataFrame(c_desc_dict)
display_scrollable_df(df_c_desc)

In [99]:
# Calls the describe method on all the d columns in df_train
d_desc_dict = {}
for num in range(1,16):
    d_desc_dict[f'd{num}'] = df_train[f'd{num}'].describe()
df_d_desc = pd.DataFrame(d_desc_dict)
display_scrollable_df(df_d_desc)

In [100]:
# Calls the describe method on all the v columns in df_train
v_desc_dict = {}
for idx, col in enumerate(df_train.columns):
    if col.startswith('v'):
        v_desc_dict[f"Column {col} at index {idx}"] = df_train.iloc[:, idx].describe()
df_v_desc = pd.DataFrame(v_desc_dict)
display_scrollable_df(df_v_desc)

In [101]:
# Calls the describe method on all the id columns in df_train
id_desc_dict = {}
for num in range(1,12):
    if num < 10:
        id_desc_dict[f'id_0{num}'] = df_train[f'id_0{num}'].describe()
    else:
        id_desc_dict[f'id_{num}'] = df_train[f'id_{num}'].describe()
df_id_desc = pd.DataFrame(id_desc_dict)
display_scrollable_df(df_id_desc)

In [102]:
# Looks at the first five rows of data from columns with the float64 datatype in df_test
df_test.select_dtypes(include=['float64']).head()

transactionamt  card2  card3  card5  addr1  addr2   dist1  \
transactionid                                                              
3663549                 31.95  111.0  150.0  226.0  170.0   87.0     1.0   
3663550                 49.00  111.0  150.0  226.0  299.0   87.0     4.0   
3663551                171.00  574.0  150.0  226.0  472.0   87.0  2635.0   
3663552                284.95  360.0  150.0  166.0  205.0   87.0    17.0   
3663553                 67.95  452.0  150.0  117.0  264.0   87.0     6.0   

               dist2   c1   c2   c3   c4   c5   c6   c7   c8   c9  c10  c11  \
transactionid                                                                 
3663549          NaN  6.0  6.0  0.0  0.0  3.0  4.0  0.0  0.0  6.0  0.0  5.0   
3663550          NaN  3.0  2.0  0.0  0.0  0.0  1.0  0.0  0.0  2.0  0.0  1.0   
3663551          NaN  2.0  2.0  0.0  0.0  0.0  5.0  0.0  0.0  4.0  0.0  2.0   
3663552          NaN  5.0  2.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  0.0  2.0   
3663553          NaN  6.0  6.0  0.0  0.0  2.0  5.0  0.0  0.0  5.0  0.0  6.0   

               c12    c13  c14     d1     d2    d3     d4    d5  d6  d7  d8  \
transactionid                                                                 
3663549        1.0  115.0  6.0  419.0  419.0  27.0  398.0  27.0 NaN NaN NaN   
3663550        1.0   12.0  2.0  149.0  149.0   7.0  634.0   7.0 NaN NaN NaN   
3663551        0.0   22.0  2.0  137.0  137.0  10.0   97.0  10.0 NaN NaN NaN   
3663552        0.0    7.0  4.0   42.0   42.0  41.0  242.0  41.0 NaN NaN NaN   
3663553        0.0   14.0  6.0   22.0   22.0   0.0   22.0   0.0 NaN NaN NaN   

               d9    d10    d11  d12  d13  d14    d15   v1   v2   v3   v4  \
transactionid                                                               
3663549       NaN  418.0  203.0  NaN  NaN  NaN  409.0  1.0  1.0  1.0  1.0   
3663550       NaN  231.0  634.0  NaN  NaN  NaN  634.0  1.0  1.0  1.0  1.0   
3663551       NaN  136.0  136.0  NaN  NaN  NaN   97.0  1.0  1.0  1.0  1.0   
3663552       NaN  242.0  242.0  NaN  NaN  NaN  242.0  1.0  1.0  1.0  1.0   
3663553       NaN   22.0   22.0  NaN  NaN  NaN   22.0  1.0  1.0  1.0  1.0   

                v5   v5   v6   v7   v8   v9  v10  v11  v12  v12  v13  v14  \
transactionid                                                               
3663549        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0   
3663550        1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663551        1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663552        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
3663553        1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   

               v15  v16  v17  v18  v19  v20  v21  v22  v23  v24  v25  v26  \
transactionid                                                               
3663549        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
3663550        0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663551        0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  2.0  2.0  1.0  1.0   
3663552        0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663553        0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   

               v27  v28  v29  v30  v31  v32  v33  v34  v35  v36  v37  v38  \
transactionid                                                               
3663549        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663550        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663551        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   
3663552        0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  2.0  2.0  2.0  2.0   
3663553        0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   

               v39  v40  v41  v42  v42  v43  v44  v45  v46  v47  v48  v49  \
transactionid                                                               
3663549        0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  

In [103]:
# Looks at the first five rows of data from columns with the int64 datatype in df_test
df_test.select_dtypes(include=['int64']).head()

transactiondt  card1
transactionid                      
3663549             18403224  10409
3663550             18403263   4272
3663551             18403310   4476
3663552             18403310  10989
3663553             18403317  18018

In [104]:
# Calls the describe method on all the card columns in df_test
test_card_desc_dict = {}
for num in range(1,7):
    test_card_desc_dict[f'card{num}'] = df_test[f'card{num}'].describe()
df_card_desc_test = pd.DataFrame(test_card_desc_dict)
display_scrollable_df(df_card_desc_test)

In [105]:
# Calls the describe method on all the addr columns in df_test
test_addr_desc_dict = {}
for num in range(1,3):
    test_addr_desc_dict[f'addr{num}'] = df_test[f'addr{num}'].describe()
df_addr_desc_test = pd.DataFrame(test_addr_desc_dict)
display_scrollable_df(df_addr_desc_test)

In [106]:
# Calls the describe method on all the dist columns in df_test
test_dist_desc_dict = {}
for num in range(1,3):
    test_dist_desc_dict[f'dist{num}'] = df_test[f'dist{num}'].describe()
df_dist_desc_test = pd.DataFrame(test_dist_desc_dict)
display_scrollable_df(df_dist_desc_test)

In [107]:
# Calls the describe method on all the c columns in df_test
test_c_desc_dict = {}
for num in range(1,15):
    test_c_desc_dict[f'c{num}'] = df_test[f'c{num}'].describe()
df_c_desc_test = pd.DataFrame(test_c_desc_dict)
display_scrollable_df(df_c_desc_test)

In [108]:
# Calls the describe method on all the d columns in df_test
test_d_desc_dict = {}
for num in range(1,16):
    test_d_desc_dict[f'd{num}'] = df_test[f'd{num}'].describe()
df_d_desc_test = pd.DataFrame(test_d_desc_dict)
display_scrollable_df(df_d_desc_test)

In [109]:
# Calls the describe method on all the v columns in df_test
test_v_desc_dict = {}
for idx, col in enumerate(df_train.columns):
    if col.startswith('v'):
        test_v_desc_dict[f"Column {col} at index {idx}"] = df_test.iloc[:, idx].describe()
df_v_desc_test = pd.DataFrame(test_v_desc_dict)
display_scrollable_df(df_v_desc_test)

In [110]:
# Calls the describe method on all the id columns in df_test
test_id_desc_dict = {}
for num in range(1,12):
    if num < 10:
        test_id_desc_dict[f'id_0{num}'] = df_test[f'id_0{num}'].describe()
    else:
        test_id_desc_dict[f'id_{num}'] = df_test[f'id_{num}'].describe()
df_id_desc_test = pd.DataFrame(test_id_desc_dict)
display_scrollable_df(df_id_desc_test)

### Missing Data
If missing data is present (ie, NaN values), what is the best way to deal with it? Should values be imputed (and if so, how)? Or should they simply be filled? How will each option will affect the ultimate outcome of your model? Design and implement a solution.

In [111]:
# Runs null_counts function on df_train and saves result to a dataframe
df_train_null_counts = null_counts(df_train)

# Filters df_train_null_counts to return a dataframe where null_fraction is greater than 0.5 and looks at resulting dataframe
df_train_null_counts_null_fraction_over_50_percent = df_train_null_counts[df_train_null_counts['null_fraction']>0.5]

# Creates list of features in df_train_null_counts_null_fraction_over_50_percent and looks at resulting list
list_df_train_features_null_fraction_over_50_percent = list(df_train_null_counts_null_fraction_over_50_percent.reset_index()['index'])

### Additional Cleaning
Depending on your data set, there may be additional cleaning you would like to do at this stage. If so, do that here.

In [112]:
# Imports necessary libraries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import VarianceThreshold
import numpy as np

#### The code in the cell below only applies for model types where the numerical data needs to be scaled
- In this case, I would encode categorical data at the same time so that I could define the columns for each separate transformation using the select_dtypes method, a less arduous process than doing it by hand

In [113]:
# Select numerical and categorical columns
#numerical_cols = df_train.select_dtypes(include=['int64', 'float64']).columns
#categorical_cols = df_train.select_dtypes(include=['object']).columns

# Define the column transformer
# preprocessor = ColumnTransformer(
#    transformers=[
#        ('num', RobustScaler(), numerical_cols),
#        ('cat', OneHotEncoder(), categorical_cols)
#    ]
#)

# Apply the transformations
# transformed_data = preprocessor.fit_transform(df_train)

# Convert the transformed data back to a DataFrame
# df_train_transformed = pd.DataFrame(transformed_data, columns=numerical_cols.tolist() + preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols).tolist())

In [114]:
# Function to identify and drop highly correlated features, as well as features with low variance
def preprocess_corr_var(df, correlation_threshold=0.9, variance_threshold=0.01):
    # Calculate the correlation matrix
    corr_matrix = df.corr().abs()
    
    # Identify pairs of highly correlated features
    upper_triangle = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    high_corr_pairs = upper_triangle.stack().reset_index()
    high_corr_pairs.columns = ['Feature_1', 'Feature_2', 'Correlation']
    high_corr_pairs = high_corr_pairs[high_corr_pairs['Correlation'] > correlation_threshold]
    
    # Create a set to keep track of features to drop
    features_to_drop = set()
    
    # Iterate over each pair of highly correlated features
    for _, row in high_corr_pairs.iterrows():
        feature_1 = row['Feature_1']
        feature_2 = row['Feature_2']
        # Drop the feature with the lower variance
        if df[feature_1].var() < df[feature_2].var():
            features_to_drop.add(feature_1)
        else:
            features_to_drop.add(feature_2)

    # Drop the identified features
    num_corr_features_to_drop = len(features_to_drop)
    print(f"{num_corr_features_to_drop} highly correlated features were dropped from the dataset")
    features_to_drop_indices = [df.columns.get_loc(feature) for feature in features_to_drop]
    df_corr_dropped = df.drop(columns=list(features_to_drop))

    # Initialize the VarianceThreshold selector
    selector = VarianceThreshold(threshold=variance_threshold)

    # Fit the selector to the data and transform the data
    df_corr_var_dropped = pd.DataFrame(selector.fit_transform(df_corr_dropped), 
                                       columns=df_corr_dropped.columns[selector.get_support()]) # returns a boolean array indicating which features are retained (True) and which are removed (False) after applying the variance threshold. This boolean array can be used to filter the columns of the original DataFrame to keep only the features that meet the variance threshold.
    
    low_variance_dropped_indices = [i for i, x in enumerate(selector.get_support()) if not x]
    # Calculate the number of features dropped due to low variance
    num_features_dropped_low_variance = len(low_variance_dropped_indices)
    print(f"{num_features_dropped_low_variance} low variance features were dropped from the dataset")
    
    return df_corr_var_dropped, corr_features_to_drop_indices, low_variance_dropped_indices


In [115]:
# df_train, df_test_high_corr_indices, df_test_low_variance_indices = preprocess_corr_var(df_train)

In [116]:
# df_test = df_test.drop(columns=df_test_high_corr_indices)
# df_test = df_test.drop(columns=df_test_low_variance_indices)

####  Save the Analytic Set
After this step, you should have a single dataframe with any inconsistencies, such as non-uniform column names and missing data, fixed. Depending on the data, the dataframe could be multiindexed as well. This is a good time to save the set. We'll load it from here during the next notebook.

Be sure to give your analytic set a unique name, as other people will be using the same repository to store their data on git. To adhere to the git repo naming conventions, prepend your initials to the filename.

In [117]:
output_loc = '../data/interim/'

In [118]:
df_train.index.name = 'transactionid'
df_train.to_csv(os.path.join(output_loc, 'df_train.csv'), index=True)

In [119]:
df_test.index.name = 'transactionid'
df_test.to_csv(os.path.join(output_loc, 'df_test.csv'), index=True)

## Verifying the Data Quality
While we're cleaning the data, it's important to give some thought to the quality.

### Data Source and Reliability
What is the origin of the data? How was it obtained? For quality assurance purposes, it's relevant to know how reliable the data is. This will help you deal with any potential data-entry errors or determine how trustworthy your eventual model will be.

- The data is gathered by Vesta's (the sponsor of the Kaggle competition) fraud protection system and digital security partners
- A transaction is labeled as fraud (isFraud=0) if there is a reported chargeback on a given card. Transactions occuring after the fraudulent one are also labeled as fraud if they are directly linked to the fraudulent transaction by attributes such as user account, email address or billing address.
- If none of above is reported and found beyond 120 days, then a transaction is labeled as not fraud (isFraud=0).
- However, it is noted, that in the real world, fraudulent activity might not be reported, e.g. cardholder was unaware of fraudulent activity on their card, or did not report it in time (beyoned the claim period, etc.) In such cases, supposed fraud might be labeled as legit, but it would be practically impossible to know. From a representative of Vesta - "We think they're unusual cases and a negligible portion."
- In regard to the dataset, this means that it is difficult to trust the complete accuracy of the labeling and does raise questions about how reliable an eventual model will be, though the sponsor doesn't think mislabeled data make up a significant slice of the data

### Error Handling
Are there any data-entry errors in the data? How can you tell? How would you characterize the overall quality of the dataset?
If appropriate, implement a solution for dealing with any errors you find.

## Outcome 

By the end of this notebook you should have an analytic data set and be ready to dive into some analysis.